### ISSUE TITLE
Unable to receive messages in app inbox for Android

### ISSUE THREAD

**Issue by mrtarunsaraswat** [CleverTap/clevertap-flutter#100]
Hi, I am unable to receive messages in app Inbox for android devices for iOS it is working fine.

**Comment by william-ct** [comment]
Hi @mrtarunsaraswat, Need the following info regarding your integration of AppInbox:-

- Are you using CT's `showInbox()` directly out of box implementation or are you custom view to show inbox messages?

- Which version of CleverTapFlutterPlugin have you implemented?

**Comment by mrtarunsaraswat** [comment]
Hi @william-ct I am using like this.
`var styleConfig = {
        'noMessageTextColor': '#000000',
        'noMessageText': 'No message(s) to show.',
        'navBarTitle': 'App Inbox'
      };`

`await CleverTapPlugin.showInbox(styleConfig);`

Previously, I was using **clevertap_plugin: ^1.3.0** but I updated **clevertap_plugin: ^1.5.0**. In both versions, I am unable to get messages.

**Comment by william-ct** [comment]
@mrtarunsaraswat The above method call to showInbox is correct. Can you clarify whether are you not able to open the AppInbox UI in your app or are you not receiving any inbox messages created via campaigns? Also for integrating app inbox have you followed the implementation provided in the [sample app ](https://github.com/CleverTap/clevertap-flutter/tree/master/example)

**Comment by mrtarunsaraswat** [comment]
@william-ct Yeah, I am able to open the app inbox the application but unable to receive the messages. It shows **No message(s) to show.** I followed the same sample app for reference.

**Comment by mrtarunsaraswat** [comment]
Hi @william-ct Any update on this?

**Comment by william-ct** [comment]
Hey @mrtarunsaraswat Can you raise a support ticket regarding this issue?
