### ISSUE TITLE
I am getting this issue for clever tap implementation

### ISSUE THREAD

**Issue by vartikaantino** [CleverTap/clevertap-flutter#103]
android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:24: error: cannot access SyncListener
      flutterEngine.getPlugins().add(new com.clevertap.clevertap_plugin.CleverTapPlugin());
                                ^
  class file for com.clevertap.android.sdk.SyncListener not found

* What went wrong:
Execution failed for task ':app:compileStageDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by randikachan** [comment]
@vartikaantino I'm also getting the same error on Flutter setup now. I don't know what's the wrong thing I have done, by step by step I followed the CleverTap integration setup.

Trying to figure out what's wrong with this.

**Comment by william-ct** [comment]
Hi @vartikaantino , This seems to be a compile time error thrown by the IDE, can you check your project's `build.gradle` file for `compileSdkVersion`, `gradle_buildTools` version mismatch? Alternatively you can try the answers poster [here](https://stackoverflow.com/questions/59177152/flutter-error-execution-failed-for-task-appcompiledebugjavawithjavac) and also solution posted in [this Github Flutter Issue](https://github.com/flutter/flutter/issues/67677). Also can you share us the project's `build.gradle`  as well as app's `build.gradle` with us. Thanks!

+ @randikachan

**Comment by apurvpandey** [comment]
I'm also getting the same error. Tried the above-mentioned suggestions, but had no luck. 
I'm integrating Flutter SDK version 1.5.1

**Comment by william-ct** [comment]
Hey @apurvpandey, Can you share your `build.gradle` file of both app's and project's?

**Comment by apurvpandey** [comment]
It has some sensitive information. So I cannot share the entire file. If you could let me know the specific information you are looking for, I can share the same.

**Comment by william-ct** [comment]
Need to know your compileSDKVersion,buildToolsVersion and gradle tools version

**Comment by apurvpandey** [comment]
compileSdkVersion 32
buildToolsVersion 33.0.0-rc2
distributionUrl=https\://services.gradle.org/distributions/gradle-7.4.2-bin.zip

**Comment by william-ct** [comment]
Hi @apurvpandey , attaching a sample project with the above configuration which you've shared along with the latest CleverTap_Flutter_Plugin V1.5.1. Can you try cloning this [sample repository from here](https://github.com/william-ct/FCM-CT.git) and check whether it's still causing issue in your app?

**Comment by avneeshkumar** [comment]
Just this `implementation 'com.clevertap.android:clevertap-android-sdk:4.4.0'` to the app level build.gradle of android.

**Comment by apurvpandey** [comment]
> Just add this `implementation 'com.clevertap.android:clevertap-android-sdk:4.4.0'` to the app level build.gradle of android.
@avneeshkumar @william-ct 
It is not part of the documentation provided for CleverTap Flutter SDK integration
Also, we should not explicitly specify/add the android or ios dependency, as we're integrating the Flutter SDK. In fact, CleverTap Flutter SDK should internally point to the respective Android or iOS SDK version.
