### ISSUE TITLE
Need Info regarding  CleverTapPlugin.setPushToken(token)

### ISSUE THREAD

**Issue by snghnishant** [CleverTap/clevertap-flutter#107]
Hey @darshanclevertap @william-ct  just wanted to understand that do I have to manually call 
```
 //  Send FCM Token for push notification from CleverTap
     CleverTapPlugin.setPushToken(token);
```
to pass Clevertap SDK the push notification token for it to work or does it happen automatically by SDK internally which sets the device token for that device in the Clevertap dashboard. I wanted to clear this doubt because I am currently passing the token manually by explicitly calling this code whenever my app starts, however, this has also made the whole Clevertap dashboard have a lot of push notification tokens on user profiles. Every new token is being stored and displayed in the dashboard making it confusing for us to use it. Adding the code and screenshot of user profiles for reference.

Also why there are too many device info profiles with different ids being created for the user even after logging in with the same device?

```dart
// Send device details for notifications
    FirebaseMessaging.instance.getToken().then((token) {
      // debugPrint("device token: $token");
      readPrefs().then((value) {
        if (value['email'] != userDataBox.getAt(0)!.email ||
            value['token'] != token) {
          // Opening app for first time / Logged in to new Account / Token Refreshed
          Map<String, String> data = {
            "email": userDataBox.getAt(0)!.email,
            "deviceOS": Platform.operatingSystem,
            "token": token!,
          };
          // update in our database
          sendFcmToken(data);
          // Send FCM Token for push notification from CleverTap
          CleverTapPlugin.setPushToken(token);
          Singular.registerDeviceTokenForUninstall(token);
          prefs.then((data) {
            data.setString('email', userDataBox.getAt(0)!.email);
            data.setString('token', token);
          });
        } else {
          debugPrint('We had already sent the Device token before');
        }
      });
    });
```
<img width="1415" alt="Screenshot 2022-06-25 at 4 19 59 PM" src="https://user-images.githubusercontent.com/38485386/175770377-d45add19-0be2-49eb-9b75-7a55e31538d6.png">

**Comment by Anush-Shand** [comment]
@snghnishant This is only required if you have your custom implementation for handling Android push notifications as mentioned in the docs otherwise the sdk handles this on it's own
