### ISSUE TITLE
The plugin `clevertap_plugin` is built using an older version of the Android plugin API

### ISSUE THREAD

**Issue by shaz-tech** [CleverTap/clevertap-flutter#11]
The plugin `clevertap_plugin` is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment. It may have undefined behaviors when Flutter is integrated into an existing app as a module.
The plugin can be updated to the v2 Android Plugin APIs

**Comment by darshanclevertap** [comment]
@shaz-tech Can you point us to some relevant documentation regarding this v2 Android Plugin APIs?

**Comment by shaz-tech** [comment]
https://flutter.dev/go/android-plugin-migration

**Comment by darshanclevertap** [comment]
@shaz-tech Thank you for sharing this. After I replied to you the other day, I did come across this link. This is a bigger change than expected and I'll have to discuss this internally with my team on how to migrate to the new Android Plugin APIs and by when? I will update this thread as soon as I have something for you.
Marking this as an enhancement for now.

**Comment by darshanclevertap** [comment]
@shaz-tech Our latest version [v1.1.3](https://pub.dev/packages/clevertap_plugin) supports the new Android Plugin APIs. Closing this now.
