### ISSUE TITLE
Issue with CleverTap Native Display

### ISSUE THREAD

**Issue by anujkapoorcg** [CleverTap/clevertap-flutter#110]
We are trying to implement CleverTap Native Display to render widgets on our home page based on analytics. For this, we created multiple Native Display campaigns (Simple, Carousal, etc.). The target segment for all the campaigns is set as "App Launched" and all the campaigns are published and running.

We integrated CleverTap Flutter SDK into our app but whenever we call the method CleverTapPlugin.getAllDisplayUnits() it is always returning a single campaign. We are not getting all the campaigns that are defined but we are always getting the last campaign we have created in the API.

Please let us know if this is a known issue. If not, what could be the reason for this? We also saw a similar issue raised on CleverTap GitHub https://github.com/CleverTap/clevertap-android-sdk/issues/48 but this was closed

**Comment by darshanclevertap** [comment]
@anujkapoorcg Do you have multiple campaigns running on the "App Launched" event? CleverTap by design only sends one Native Display campaign (the last one created) on one event to avoid spamming. If you want to show multiple widgets, you can probably use the Key-Value Pair Template and pass all the keys to display all the widgets you want to show on "App Launched" event. Or you can raise multiple events on App Launch and create different campaigns on each event.
Hope this helps!

**Comment by anujkapoorcg** [comment]
Thanks @darshanclevertap for your quick response, appreciate it.
 
Running only one Native Display campaign for one target segment is a huge limitation for us. Is this mentioned in some documentation that we missed? If not, please make sure to add this caveat to the Native Display documentation.
 
We are trying to implement the following use case using Native Display on the mobile app’s home page. There are 3 headers with Carousal widgets, inside which there can be many cards. Each card is rendered for a specific target group (event) as shown below:


![image](https://user-images.githubusercontent.com/108324628/184063456-1ed4e1e7-e728-4669-902c-5eeef246b82f.png)


All these carousal widgets had to be rendered from CleverTap Native Display and each card is targeted for a different user segment. As I understand, there could be three approaches to implement this:
 
Create 3 campaigns, one for each Header: This approach will not work because one campaign can target only one user-segment, so we won’t be able to club 3 different user segment (like cards 1,2 & 3) in the same campaign.
Create separate campaigns for each card: This approach will not work because cards 3, 5, 7 belong to same event “App Installed” and we can create only one  Native Display campaign per event, as you mentioned in your email.
Club All cards with same event into a carousal campaign: Let’s say we club the cards with same event (say cards 2, 4) into a single Native Display campaign with type Carousal. Now at the app side, there is no way to identify which header these cards belong to. We won’t be able to identify if card 1 belong to Header 1 or Header 2 at the app side. There is no field which can identify card-wise in a carousal campaign. Also, we cannot use custom key-value pair because it is not segregated card-wise it is common for a campaign.
 
Do you have any other suggestion on how to implement this scenario? Please let us know.

**Comment by darshanclevertap** [comment]
> Also, we cannot use custom key-value pair because it is not segregated card-wise it is common for a campaign.

Why not? You can provide the key name as Header 1 and in the value pass the entire widget details as JSON String. Capture the JSON string in the App and render the UI of the carousel. So for the App Launched event, you can send the following KV Pairs -

```
Header 1 <> {JSON for Widget 2}
Header 2 <> {JSON for Widget 4}
```

Using the Native Display type Carousel does not give any added advantage right now because it only gives the data on the SDK end in a structured manner and the SDK does not render the UI.

**Comment by anujkapoorcg** [comment]
@darshanclevertap the problem is that the campaigns will be managed by the marketing team not by the developers. The marketing team will not be able to change the image and text inside the JSON and there would always be a dependency on the developers. Is there any solution where a non-developer user can edit the campaign?

**Comment by darshanclevertap** [comment]
@anujkapoorcg then I'd just use the following structure in KV Pairs

```
HeaderName <> Header1
Widget Text <> Text
Widget Image <> Image URL
.
.
HeaderName <> Header2
Widget Text2 <> Text2
Widget Image2 <> Image URL2
.
.
```

Then the developers can get the respective Keys and Values to render the Card in the App

**Comment by anujkapoorcg** [comment]
@darshanclevertap Thank you for the suggestion, this seems feasible. One more question:
What about the image, do we have to upload the images somewhere else (like aws s3) and then provide the image URL in KV pair? Because that will also create dependency for the marketing team. Is there any way we can upload the images on the CleverTap and provide the URL from there?

**Comment by darshanclevertap** [comment]
@anujkapoorcg For now you can only upload to some CDN like AWS S3 and use that. I will take up the request to host images on CleverTap itself with the product team 👍🏾
