### ISSUE TITLE
Click on push notification not triggered methods

### ISSUE THREAD

**Issue by maxim-ivanchuk-idf** [CleverTap/clevertap-flutter#111]
When i am sending notification from clever tap panel , notification receive is detected by FirebaseMessaging.onMessage (when app in foreground) and FirebaseMessaging.onBackgroundMessage(when app in background), but FirebaseMessaging.onMessageOpenedApp.listen is not working while opening/click on notification.

CleverTapPlugin().setCleverTapInboxMessagesDidUpdateHandler(() {});
CleverTapPlugin().setCleverTapPushAmpPayloadReceivedHandler((map) {});
CleverTapPlugin().setCleverTapInboxNotificationButtonClickedHandler((map) {});
CleverTapPlugin().setCleverTapInAppNotificationDismissedHandler((map) {});
CleverTapPlugin().setCleverTapPushClickedPayloadReceivedHandler((map) {});
CleverTapPlugin().setCleverTapInAppNotificationButtonClickedHandler((map) {});

this methods all not triggered 

@darshanclevertap

**Comment by dharmendra79** [comment]
@maxim-ivanchuk-idf did you find the solution??

**Comment by dharmendra79** [comment]
@maxim-ivanchuk-idf I am having the same issue and not able to trigger the click handle.

**Comment by maxim-ivanchuk-idf** [comment]
@dharmendra79 i used flutterLocalNotificationsPlugin for showing notification in android

**Comment by dmaheshwari2209** [comment]
what about IOS ?

**Comment by shivamsharma2710** [comment]
Hi @maxim-ivanchuk-idf @dmaheshwari2209 

If the issue is still unresolved, please feel free to reopen the ticket and provide the relevant information.
