### ISSUE TITLE
Notifications not showing while app in foreground iOS

### ISSUE THREAD

**Issue by AhmedEzio47** [CleverTap/clevertap-flutter#112]
Hi all, I've successfully integrated CleverTap notifications as per the documentation, but I'm facing a minor issue, notifications won't show while the app is in the foreground, in the case of iOS, is this behaviour expected? or am I missing something?

This is how I init the plugin
void init() {
    CleverTapPlugin.createNotificationChannel(
      "walaone_clevertap",
      "walaone_clevertap-notification",
      "walaone_clevertap-push-notification",
      3,
      true,
    );
    CleverTapPlugin.setDebugLevel(0);
    CleverTapPlugin.initializeInbox();
    // CleverTapPlugin.resumeInAppNotifications();
    CleverTapPlugin.enableDeviceNetworkInfoReporting(true);
    if (Platform.isIOS) {
      CleverTapPlugin.registerForPush();
      firebaseMessaging.getAPNSToken().then((token) {
        if (token != null) CleverTapPlugin.setPushToken(token);
        Logger.debugLog('APN CleverTap Token: $token');
      });
    }
    if (Platform.isAndroid) {
      firebaseMessaging.getToken().then(
        (firebaseToken) {
          CleverTapPlugin.setPushToken(firebaseToken!);
          Logger.debugLog('CleverTap Token: $firebaseToken');
        },
      );
    }
  }
  Thank you

**Comment by tp-coderbabu** [comment]
can you also share the IOS swift implementation part also?

**Comment by darshanclevertap** [comment]
@AhmedEzio47 Is this still an issue?

**Comment by Mohanedy98** [comment]
I can confirm that this still exists on iOS

**Comment by nishant-clevertap** [comment]
Hi @Mohanedy98,

If you’d like to have iOS display your notification while your app is running in the foreground, you’ll need to implement the `UNUserNotificationCenterDelegate` method `userNotificationCenter(_:willPresent:withCompletionHandler:)`, which is called when a notification is delivered to your app while it’s in the foreground. 

Make sure you have added following code in your AppDelegate.m file:
1. Set `UNUserNotificationCenter` delegate to self in `didFinishLaunchingWithOptions:` method:
```
UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
center.delegate = self;
```
2. Add following method in AppDelegate.m:
```
- (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler{
    completionHandler(UNAuthorizationOptionSound | UNAuthorizationOptionAlert | UNAuthorizationOptionBadge);
}
```

You can also refer our sample app: https://github.com/CleverTap/clevertap-flutter/blob/master/example/ios/Runner/AppDelegate.m

Do let us know if this will work. Thanks.
