### ISSUE TITLE
CleverTap Native Display Issue

### ISSUE THREAD

**Issue by anujkapoorcg** [CleverTap/clevertap-flutter#113]
I have 3 Native Display Campaigns running:
Campaign 1: where Who = "App Launched"
Campaign 2: where Who = "Event 1"
Campaign 3: where Who = "Event 2"

Event 1 and Event 2 both are triggered from the Flutter main function

```
Future<void> main() async{

var eventData = {
    'Key':    'Value'
  };

CleverTapPlugin.recordEvent("Event 1", eventData);
CleverTapPlugin.recordEvent("Event 2", eventData);
runApp(const MyApp());
}
```

When I call `CleverTapPlugin.getAllDisplayUnits()` I receive only Campaign 2 and Campaign 3 in the response but not Campaign 1. This seems to be a bug in CleverTap because campaign 1 is "App Launched" and it should always be triggered.

Please note I have tried:
1. Rerunning/relaunching/killing the app on the emulator and on the device.
2. I saw on the CleverTap dashboard the event counter for App Launched is increased every time I launch the app but getAllDisplayUnits() does not return Campaign 1

Surprising thing is that if I comment out the 2 recordEvent calls, I start getting Campaign 1 in the response. 

Please Help.

**Comment by anujkapoorcg** [comment]
@darshanclevertap could you please help here?

**Comment by darshanclevertap** [comment]
@anujkapoorcg This should not ideally happen. 

This seems like a back end issue to me. Can you raise a support ticket via the dashboard for this and add this GitHub issue link in that as well. I'll try and take this up on priority.

Thanks!

**Comment by anujkapoorcg** [comment]
@darshanclevertap Ticket #[107565] raised via dashboard.

**Comment by darshanclevertap** [comment]
@anujkapoorcg We have raised an internal support ticket for this and I have set the context of the issue. We will get back to you as soon as we get a response from the back end team

**Comment by anujkapoorcg** [comment]
Hi @darshanclevertap , Any update on this?

**Comment by darshanclevertap** [comment]
The back end is still working on this. Give me a day to get the latest update on this. Sorry for the delay here

**Comment by prince-kumar** [comment]
@darshanclevertap  can you please help me with this ? We have a critical release to be decided on top of it. We are not able to see the cards shown on the basis of the CT custom events. 

If this does not work, we will be forced to move to other tools.

**Comment by darshanclevertap** [comment]
@anujkapoorcg @prince-kumar I have escalated this internally. Someone from our support team will be reaching out to you shortly. Sorry for the delay
