### ISSUE TITLE
Add multi-instance support to Flutter package

### ISSUE THREAD

**Issue by AhmedEzio47** [CleverTap/clevertap-flutter#116]
Multi-instance support is a handy feature, but it's absent in the Flutter version of the SDK, so please add it. In the meantime, can I use the native implementation by utilizing method channels? I tried but it seems I have to return the created (additional instance) in the method channel which I think is impossible.

**Comment by darshanclevertap** [comment]
@AhmedEzio47 Currently we do not support creating multiple instances in the Flutter SDK, but we will take this up internally with our product team

**Comment by darshanclevertap** [comment]
@AhmedEzio47 We are not going to pick this up in the near future. Please raise a support request via CleverTap Dashboard so that it can reach the correct team internally as request.
