### ISSUE TITLE
Transparent Images not working in Native Display

### ISSUE THREAD

**Issue by anujkapoorcg** [CleverTap/clevertap-flutter#117]
Steps to reproduce:
1. Create a native display campaign with a single message with an icon or carousal
2. Upload an image with a transparent background to the slide
3. Call CleverTapPlugin.getAllDisplayUnits()

Expected Results:
In the response of CleverTapPlugin.getAllDisplayUnits() the URL should be of the same image which was uploaded with transparent background.

Actual Result:
In the response of CleverTapPlugin.getAllDisplayUnits(), in the url provided in the media tag, the transparent background of the image is replaced with white background

**Comment by darshanclevertap** [comment]
@anujkapoorcg This is a CleverTap Dashboard issue as well, please raise a support ticket and mention this Github Issue and I will expedite this

**Comment by anujkapoorcg** [comment]
Thanks @darshanclevertap. Ticket #108722 raised on dashboard
