### ISSUE TITLE
App crashed frequently on didRegisterForRemoteNotificationsWithDeviceToken

### ISSUE THREAD

**Issue by iobart** [CleverTap/clevertap-flutter#118]
after upgrading clevertap to version 1.5.1  the application stops 
I currently have my sdk 2.18.0 and flutter version 3.3.1
<img width="560" alt="Captura de Pantalla 2022-09-22 a la(s) 4 17 52 p m" src="https://user-images.githubusercontent.com/46167338/191852843-3fc93343-ff49-47f7-bacf-5994857696b9.png">
this is the error that occurs
<img width="696" alt="Captura de Pantalla 2022-09-22 a la(s) 4 13 22 p m" src="https://user-images.githubusercontent.com/46167338/191852503-c7ea6208-705a-4d63-bb3a-54682e97326c.png">

**Comment by nishant-clevertap** [comment]
Hi @iobart,

Can you please update to our latest Flutter SDK v1.5.5- https://github.com/CleverTap/clevertap-flutter/releases/tag/1.5.5 and check if you are facing crash or not. 

If you are still facing crash, please do share the stack trace and steps which produces crash to investigate it further.

Thanks.

**Comment by nishant-clevertap** [comment]
@iobart Is this still an issue? If yes, reopen the issue with the detailed stack trace and steps to reproduce. Thanks.
