### ISSUE TITLE
Planning to update native plugins?

### ISSUE THREAD

**Issue by junaid1460** [CleverTap/clevertap-flutter#119]
Last release was 5 months ago, there has been so many changes in native side

**Comment by darshanclevertap** [comment]
@junaid1460 We do keep our Flutter SDKs updated. Support for Android 13 will be coming out soon.

**Comment by shivamsharma2710** [comment]
@junaid1460 We have the android 13 support in [CleverTap Flutter v1.6.0](https://github.com/CleverTap/clevertap-flutter/releases/tag/1.6.0). 

Closing this issue if you have any release related query, please follow [release notes page](https://github.com/CleverTap/clevertap-flutter/releases).
