### ISSUE TITLE
Not getting Native Display Campaigns when a custom event triggers.

### ISSUE THREAD

**Issue by bhanumniyo** [CleverTap/clevertap-flutter#127]
I created a Native Display Campaign where in the "WHO" section I have added a custom event to trigger the campaign. This custom event gets triggered at app launch itself . In the Clevertap dashboard I can see that that custom event is being logged successfully but still when I use  - 

`List? displayUnits = await CleverTapPlugin.getAllDisplayUnits();`
displayUnits List is empty.
The issue happens only when I install the app for the very first time and when I run the app again I get the campaign. 
But if I use "App Launched" event in place of the custom event I get the campaign the  first time itself.

My question is even when a custom event has been triggered successfully then why I don't receive  the campaign the first time.
Why do I have the run the app again to receive that campaign

**Comment by darshanclevertap** [comment]
@bhanumniyo this is similar to #113 Please see my [comment here](https://github.com/CleverTap/clevertap-flutter/issues/113#issuecomment-1238900275)
