### ISSUE TITLE
Clevertap Plugin won't work in Flutter Module

### ISSUE THREAD

**Issue by tamim-mm** [CleverTap/clevertap-flutter#134]
A Flutter app can be used as a module in an existing native app. 
https://docs.flutter.dev/development/add-to-app/android/project-setup

Clevertap plugin works fine in full-flutter app(standalone mode). But when the Flutter project is used module, it's giving us this error.

```
/Users/***/AndroidStudioProjects/***/flutterModule/.android/Flutter/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:19: error: cannot access SyncListener
      flutterEngine.getPlugins().add(new com.clevertap.clevertap_plugin.CleverTapPlugin());
                                ^
  class file for com.clevertap.android.sdk.SyncListener not found
```

We have added the Clevertap dependencies in our native app's build.gradle file, as suggested here
https://docs.flutter.dev/development/add-to-app/android/plugin-setup

**Comment by shivamsharma2710** [comment]
Hi @tamim-mm 

Thanks for reporting the issue. Please answer the following questions:
1) CleverTap Native SDK version?
2) CleverTap Flutter plugin version?

**Comment by tamim-mm** [comment]
Hi @shivamsharma2710

Native: 
implementation 'com.clevertap.android:clevertap-android-sdk:4.6.3'

Flutter Plugin:
clevertap_plugin: ^1.5.4

**Comment by tamim-mm** [comment]
To reproduce this, you may create a Flutter project and use it as a module in a native android app.

https://docs.flutter.dev/development/add-to-app/android/project-setup

**Comment by shivamsharma2710** [comment]
@tamim-mm Thanks for sharing the details. We will check this issue.

**Comment by tamim-mm** [comment]
I've found a way to run the plugin. 

When I add **implementation 'com.clevertap.android:clevertap-android-sdk:4.6.3'** in /.android/build.gradle it works. 

But it's not a solution because ".android" (not android) folder is auto generated when you are using Flutter project as a module, and this folder will be reset whenever you run flutter pub get.

Hope it helps you to find the real issue @shivamsharma2710

**Comment by shivamsharma2710** [comment]
Hi @tamim-mm 

Latest CleverTap plugin version doesn't support **add-to-app** feature to embed a flutter module in an existing app.

We'll be supporting **add-to-app** in the upcoming release due in few days.

**Comment by shivamsharma2710** [comment]
Closing this ticket as we've added the [add-to-app](https://docs.flutter.dev/development/add-to-app) support in the recent [release v1.5.5.](https://github.com/CleverTap/clevertap-flutter/releases/tag/1.5.5)
