### ISSUE TITLE
Push notifications not come to IOS in foreground 

### ISSUE THREAD

**Issue by maxim-ivanchuk-idf** [CleverTap/clevertap-flutter#135]
Push notifications not come to IOS in foreground, but for background and terminate  all work correctly

**Comment by maxim-ivanchuk-idf** [comment]
@darshanclevertap  clevertap_plugin: 1.5.4

**Comment by maxim-ivanchuk-idf** [comment]
import UIKit
import Flutter
import Firebase
import flutter_downloader
import CleverTapSDK
import clevertap_plugin


@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
    override func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) -> Bool {
        FirebaseApp.configure()
        GeneratedPluginRegistrant.register(with: self)
        CleverTap.autoIntegrate()
        CleverTapPlugin.sharedInstance()?.applicationDidLaunch(options: launchOptions)
        FlutterDownloaderPlugin.setPluginRegistrantCallback(registerPlugins)
        return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    }
    
    
    override func userNotificationCenter(
        _ center: UNUserNotificationCenter,
        willPresent notification: UNNotification,
        withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
            CleverTap.sharedInstance()?.handleNotification(
                withData: notification.request.content.userInfo,
                openDeepLinksInForeground: true)
            completionHandler([.badge, .sound, .alert])
        }
}

private func registerPlugins(registry: FlutterPluginRegistry) {
    if (!registry.hasPlugin("FlutterDownloaderPlugin")) {
        FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "FlutterDownloaderPlugin")!)
    }
}

**Comment by maxim-ivanchuk-idf** [comment]
Sorry, i was found ) 
i forgot add 
 UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate

**Comment by nishant-clevertap** [comment]
Great, Closing this issue.
