### ISSUE TITLE
Foreground and Background message handler not getting invoked for iOS push notification with flutter version 3.3.4 and clevertap version 1.5.4

### ISSUE THREAD

**Issue by appyshah08** [CleverTap/clevertap-flutter#137]
Flutter Version : 3.3.4 
Clevertap Version : 1.5.4

For iOS push notification the background and foreground notification are not getting invoked.

**Comment by nishant-clevertap** [comment]
Hi @appyshah08,

We are investigating the issue, could you help me with some questions:
1. Have you implemented firebase and are you using firebase foreground/background handlers?
2. Have you faced this issue in earlier CleverTap version also?

**Comment by appyshah08** [comment]
We are not using firebase.We suspect clevertap also uses firebase by default for sending notification.We are implementing for first time.

**Comment by nishant-clevertap** [comment]
Hi @appyshah08,

We have checked the behaviour in our sample app where foreground and background handlers are getting invoked with latest flutter version 3.3.9 and CleverTap version 1.5.4. 
Refer: https://github.com/CleverTap/clevertap-flutter/blob/master/example/ios/Runner/AppDelegate.m

Make sure to add UNUserNotificationCenter delegate to self before sending notification as added in sample AppDelegate file, and implement following delegate methods:
1. For foreground-  willPresentNotification:
2. For background- didReceiveNotificationResponse:

Thank you.

**Comment by appyshah08** [comment]
thanks issue is fixed by using the solution suggested by the team.
