### ISSUE TITLE
docs: `setPushToken` is document for `FCM` but what will behaviour in case of iOS. 

### ISSUE THREAD

**Issue by DK070202** [CleverTap/clevertap-flutter#141]
- This method is documented for setting the `FCM` token, I had doubts that In the case of iOS still, it will use FCM, or we have to set the APNS token. 

```dart
  /// Set the FCM Token for Push Notifications
  static Future<void> setPushToken(String value) async {
    return await _channel.invokeMethod('setPushToken', {'token': value});
  }
```
 
-  If I just use `CleverTapPlugin.registerForPush` then I can see this Log in the console from CT iOS SDK, but it seems like this `FCM` token. 
 
<img width="1032" alt="Screenshot 2023-01-04 at 11 11 47 PM" src="https://user-images.githubusercontent.com/78605453/210616886-ee36d25e-f21d-4c7e-8ebb-9cc0d5ba1468.png">

**Comment by nishant-clevertap** [comment]
Hi @DK070202,

Use `setPushToken` method for setting FCM token in Android only. In iOS when `CleverTapPlugin.registerForPush` is called and `autoIntegrate` is used in AppDelegate then we register the APNs device token at our end itself, so no need to call `setPushToken` for iOS side.

**Comment by DK070202** [comment]
> Hi @DK070202,
> 
> Use `setPushToken` method for setting FCM token in Android only. In iOS when `CleverTapPlugin.registerForPush` is called and `autoIntegrate` is used in AppDelegate then we register the APNs device token at our end itself, so no need to call `setPushToken` for iOS side.

Thank @nishant-clevertap
