### ISSUE TITLE
Error APNS bad token with app in TF

### ISSUE THREAD

**Issue by phucphamwolf** [CleverTap/clevertap-flutter#169]
When I push notification with app in debug mode I get it, but when I push notification with app on TF I get error APNS bad token

**Comment by nishant-clevertap** [comment]
Hi @phucphamwolf,

Which provisioning profile are you using before archiving the app? Also have you followed all the steps correctly mentioned in docs: https://developer.clevertap.com/docs/push-notifications-ios#step-1-configure-push-notifications, verify once if you have uploaded production push certificates if using production mode.

Thanks.

**Comment by phucphamwolf** [comment]
Thanks @nishant-clevertap. I fixed it.
