### ISSUE TITLE
Branch integration

### ISSUE THREAD

**Issue by ganeshrvel** [CleverTap/clevertap-flutter#17]
According to the documentation, it is possible to integrate CleverTap and Branch together. 
Doc link: https://developer.clevertap.com/docs/branch

How can we do the same in Flutter?

Regards!

**Comment by darshanclevertap** [comment]
@ganeshrvel The `getCleverTapAttributionIdentifier()` method mentioned in our documentation is present in Dart as well. You can use that to get the Attribution Identifier and pass it to [Branch](https://pub.dev/packages/flutter_branch_sdk)

If you face any issues, you can reach out to our support team from the Dashboard directly and someone from our team will help you out at the earliest.
