### ISSUE TITLE
Is there any difference in config in IOS when using apns push mode development/product

### ISSUE THREAD

**Issue by phucphamwolf** [CleverTap/clevertap-flutter#170]
Is there any difference in config in IOS when using apns push mode development/product

**Comment by nishant-clevertap** [comment]
Hi @phucphamwolf,

Yes, you can have only one active push certificate at a time. You need to upload production push certificates when using apns push mode production. Refer doc for more details: https://developer.clevertap.com/docs/push-notifications-ios#step-1-configure-push-notifications

**Comment by phucphamwolf** [comment]
Thanks @nishant-clevertap. I fixed it.
