### ISSUE TITLE
How to listen for an event with an Incoming Notification?

### ISSUE THREAD

**Issue by phucphamwolf** [CleverTap/clevertap-flutter#173]
How to listen for an event with an Incoming Notification. I want to handle the feature, not the notification

**Comment by nishant-clevertap** [comment]
@phucphamwolf 
When app is in foreground, you can use `willPresentNotification` method. Refer apple doc: https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/1649518-usernotificationcenter

**Comment by phucphamwolf** [comment]
Thanks @nishant-clevertap.
