### ISSUE TITLE
Support for Flutter Web

### ISSUE THREAD

**Issue by amankr** [CleverTap/clevertap-flutter#182]
Currently the sdk throws exception for web platform.
Is there a plan to add support for flutter web platform ?

**Comment by darshanclevertap** [comment]
Hi @amankr we are researching on adding Flutter Web support to our Flutter plugin. But to raise this to the right team, I would suggest reaching out to your CSM or raising a support request via the Dashboard. In the top right corner of the CleverTap Dashboard, click on *Need Help?* -> *Create a support ticket*
