### ISSUE TITLE
Wrong data types is used in _platformCallHandler

### ISSUE THREAD

**Issue by shubh-SB** [CleverTap/clevertap-flutter#185]
When `_platformCallHandler` is called from native iOS App, for method of `onDisplayUnitsLoaded`  list is used to parse the incoming data. Line number 102
`List<dynamic>? args = call.arguments;`
But in my case I am getting Map Object in call.arguments. 
`{adUnits: [{content: [{action: .......}]}`
Which is breaking the SDK And in turn Clevertap SDK is not calling my callback in my application.

Request you to fix this at earliest.
Thanks

**Comment by nishant-clevertap** [comment]
Hi @shubh-SB,
This has been already fixed in v1.6.1. Release link: https://github.com/CleverTap/clevertap-flutter/releases/tag/1.6.1
Could you try updating to v1.6.1 or above and see if it is resolved or not?

**Comment by shubh-SB** [comment]
Thanks for replying

I am also getting this crash because of CleverTap in my iOS app crashlytics. 
```
Fatal Exception: NSInternalInconsistencyException
Sending a message before the FlutterEngine has been run.
```
Is it fixed? And if its fixed, then which version it is fixed. I can not use the latest version of clvertap since it requires me to update my minimum deployment target version of iOS.

Thank you

**Comment by shubh-SB** [comment]
Alright
