### ISSUE TITLE
Error while running app

### ISSUE THREAD

**Issue by innerk** [CleverTap/clevertap-flutter#186]
Hi, after installing the dependencies for android and running the app in debug mode, i'm having this error 

E/MethodChannel#clevertap_plugin/dart_to_native(10970): Failed to handle method call
E/MethodChannel#clevertap_plugin/dart_to_native(10970): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference

PlatformException(CleverTapPlugin, CleverTap Instance is not initialized, null, null)

this is my code:

`late CleverTapPlugin _clevertapPlugin;

  @override
  void initState() {
    super.initState();
        
    initPlatformState();
    activateCleverTapFlutterPluginHandlers();
    CleverTapPlugin.setDebugLevel(3);

/*     var stuff = ["bags", "shoes"];
    var profile = {
      'Name': 'Captain America',
      'Identity': '100',
      'Email': 'captain@america.com',
      'Phone': '+14155551234',
      'stuff': stuff
    };

    CleverTapPlugin.recordEvent("Send Basic Push", profile); */
  }`

is there any step i'm doing wrong?

**Comment by shivamsharma2710** [comment]
Hi @innerk 

Which version of CleverTap Flutter SDK you're using?

**Comment by innerk** [comment]
i'm using

**Comment by innerk** [comment]
I'm using clevertap_plugin: 1.7.0 with:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.6 21G115 darwin-x64, locale en-CL)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)

**Comment by innerk** [comment]
downgraded to clevertap_plugin: 1.6.1
and works fine, thanks!
