### ISSUE TITLE
App freezes when opening Inbox functionality on iOS (version 1.7.0)

### ISSUE THREAD

**Issue by tiagostorch** [CleverTap/clevertap-flutter#188]
Hello,

I'm experiencing an issue with the CleverTap Inbox functionality on iOS. Whenever I try to open the Inbox, the app freezes and no error message is displayed in the console. However, if I open and close the app a few times (usually 2 or 3), the functionality starts working properly.

I'm using version 1.7.0 of the SDK, and my device is running the latest version of iOS. Here are the steps to reproduce the problem:

1- Open the CleverTap app on iOS.
2 - Navigate to the Inbox section.
3 - When attempting to open the Inbox functionality, the app freezes without displaying any error message in the console.
4 - Close the app and repeat steps 1-3 two or three more times.
5 - After a few attempts, the Inbox functionality starts working normally.

Furthermore, I haven't come across any similar issues reported previously.

I would greatly appreciate it if you could investigate and resolve this problem, as the Inbox functionality is crucial for the user experience in our app.

Thank you for your attention.

**Comment by akashvercetti** [comment]
@tiagostorch we will investigate this and keep you updated 👍

**Comment by akashvercetti** [comment]
@tiagostorch We have released a potential fix for this in our latest release v1.8.0. Please try updating to the latest version.
https://github.com/CleverTap/clevertap-flutter/releases/tag/1.8.0

**Comment by tiagostorch** [comment]
> @tiagostorch We have released a potential fix for this in our latest release v1.8.0. Please try updating to the latest version. https://github.com/CleverTap/clevertap-flutter/releases/tag/1.8.0

Hi @akashvercetti ,

I'm glad to announce that we've resolved the issue that was causing the app to freeze. After the recent fix, the app should now be running smoothly without any more freezing or crashing.

However, I've noticed that I haven't received any messages in my inbox since the fix was implemented. If you have any questions, feedback, or encounter any other issues, please don't hesitate to reach out. I'm here to assist and ensure everything is working as expected.

Thank you all for your patience and understanding. Let's continue working together to improve the app and deliver the best experience to our users.

**Comment by akashvercetti** [comment]
@tiagostorch we have identified the source of this issue and are in middle of fixing/testing it. Please expect a release for this next week 👍.

**Comment by tiagostorch** [comment]
> @tiagostorch we have identified the source of this issue and are in middle of fixing/testing it. Please expect a release for this next week 👍.

any updata about this fix?

**Comment by akashvercetti** [comment]
@tiagostorch We have released a fix for this in our latest release v.1.8.1 https://github.com/CleverTap/clevertap-flutter/releases/tag/1.8.1

**Comment by tiagostorch** [comment]
> @tiagostorch We have released a fix for this in our latest release v.1.8.1 https://github.com/CleverTap/clevertap-flutter/releases/tag/1.8.1

Thank you, I will perform the tests and give you feedback.
