### ISSUE TITLE
iOS foreground notifications not working

### ISSUE THREAD

**Issue by MuTe33** [CleverTap/clevertap-flutter#190]
Hi there!

we're using FCM and Clevertap for push notifications. Everything is working as expected for both iOS and Android for every state (foreground, background and terminated), except for iOS foreground. 

For Android foreground push notifications both from Clevertap and FCM the `FirebaseMessaging.onMessage` handler is being triggered and I can handle it. 

But for iOS, only FCM triggers the handler when in foreground. For Clevertap, there is not even a single reaction from the app. Even when setting `Clevertap.setDebugLevel(3)` - highest - doesn't output anything. 

What can be the reason for this? How can this be solved? There is no mention in your documentation regarding this. Any support is much appreciated.

Some technical details: 

Clevertap version: `1.6.1`
iOS Version: 16.2
Flutter version output:
```
Flutter 3.7.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2ad6cd72c0 (4 months ago) • 2023-03-08 09:41:59 -0800
Engine • revision 1837b5be5f
Tools • Dart 2.19.4 • DevTools 2.20.1
```

**Comment by nishant-clevertap** [comment]
Hi @MuTe33,
Can you try adding UNUserNotificationCenter delegate to self before sending notification as added in our sample AppDelegate file, and implement `willPresentNotification:` delegate method to receive notification is foreground. Sample app: https://github.com/CleverTap/clevertap-flutter/blob/master/example/ios/Runner/AppDelegate.m

**Comment by MuTe33** [comment]
Awesome, this did work indeed! I'd suggest adding such an important information on the documentation. It's very hidden and not obvious, especially for the Flutter setup. 

For anyone interested, this is how the Swift code looks like:

```
import UIKit
import Flutter
import CleverTapSDK
import clevertap_plugin
@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    
    CleverTap.autoIntegrate()
    registerForPush()
  
    CleverTapPlugin.sharedInstance()?.applicationDidLaunch(options: launchOptions)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  func registerForPush() {
      UNUserNotificationCenter.current().delegate = self
  }

  override func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
    completionHandler([.sound, .alert, .badge])
  }
}
```

**Comment by darshanclevertap** [comment]
@MuTe33 Thanks for pointing this out, we'll add it to our Flutter documentation
