### ISSUE TITLE
Push notifications are not displayed

### ISSUE THREAD

**Issue by GuilleTul** [CleverTap/clevertap-flutter#193]
Hi team, I can't show the notifications that are sent from the Clevertap dashboard. I did all the configurations as the documentation says, I linked with Firebase, I added the meta-data in the Manifest, everything, when I send the push, in the console I see the following message:
```
D/CleverTap:CTRM(10857): received a message from Firebase
D/CleverTap:PushProvider(10857):  [PushType:FCM] Found Valid Notification Message
V/CleverTap:CTRM(10857): Notification payload does not have a fallback key.
V/CleverTap:CTRM(10857): got a signal to kill receiver and timer because isRenderFallback is false
V/CleverTap:CTRM(10857): informing OS to kill receiver...
V/CleverTap:CTRM(10857): informed OS to kill receiver...
V/CleverTap:CTRM(10857): receiver was alive for 0 seconds
```
When I use the FCM to send the notification from Firebase, the notification arrives and displays correctly

![Captura de pantalla 2023-07-19 a la(s) 17 59 48](https://github.com/CleverTap/clevertap-flutter/assets/112665768/eeb2dad6-e01c-4f9d-8cb8-cb76bf188377)

Flutter 3.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 796c8ef792 (5 weeks ago) • 2023-06-13 15:51:02 -0700
Engine • revision 45f6e00911
Tools • Dart 3.0.5 • DevTools 2.23.1
clevertap_plugin: ^1.8.0

I appreciate your help

**Comment by shivamsharma2710** [comment]
Hi @GuilleTul,

How are you handling the notifications sent from the CleverTap dashboard? Could you please share your approach? Additionally, please provide the complete logs you receive when you receive a push notification.

**Comment by GuilleTul** [comment]
Hi @shivamsharma2710 Sorry, last week I had responded but it was not published.
The error was mine, I did not have the credentials correctly configured (CLEVERTAP_ACCOUNT_ID and CLEVERTAP_TOKEN) in the Manifest.
thanks
