### ISSUE TITLE
Setting up CleverTap for Different Flavors of Project

### ISSUE THREAD

**Issue by ShashankSMayya** [CleverTap/clevertap-flutter#194]
So we have a flutter project with different flavors (dev,prod) as of now. We are using Flutter Flavorizer to handle flavoring of the app. Say we create two projects in CleverTap for two flavors with dev and prod, How can we setup this in the respective apps and flavors?

**Comment by GuilleTul** [comment]
Hi @shivamsharma2710 I have fixed the issue, I had the credentials configured wrong in the manifest (CLEVERTAP_ACCOUNT_ID and CLEVERTAP_TOKEN)

Thanks

**Comment by shivamsharma2710** [comment]
Thanks for the update. Closing this ticket. Feel free to reach out, if you need further assistance.
