### ISSUE TITLE
getAppLaunchNotification not implemented in iOS

### ISSUE THREAD

**Issue by lachezartodorov** [CleverTap/clevertap-flutter#198]
Looks like the `getAppLaunchNotification` method is missing implementation in iOS and this just breaks the app on multiplatform applications.
On the other side ... if it's implemented only in Android, it's totally useless for multiplatform use, with is the main purpose of Flutter.
Anyway, giving some details:

Platform: iOS
clevertap_plugin: 1.8.1
CleverTap-iOS-SDK: 5.1.2

![IMG_1545711703A9-1](https://github.com/CleverTap/clevertap-flutter/assets/38905492/f4d1fc5b-6ecc-4428-af30-08691f9df0c4)

**Comment by shivamsharma2710** [comment]
Hi @lachezartodorov,

The `getAppLaunchNotification()` method is only available for Android; we intentionally do not support it for the iOS platform. Instead, to manage notification clicks on iOS, you can depend on the `pushClickedPayloadReceived` handler regardless of whether the app is in the foreground, background, or has been terminated (killed). 

If you refer to our [documentation](https://developer.clevertap.com/docs/flutter-push-notification#android-platform-handle-notification-clicks-when-the-app-is-killed), you will find that this information is already documented. Be sure to implement a platform check before using the `getAppLaunchNotification()` method.

**Comment by lachezartodorov** [comment]
It would be great if you include the check in the documentation. It will make things more clear.
I called back to `getAppLaunchNotification` method, because for some reason `pushClickedPayloadReceived` doesn't get called on app launch in iOS.

**Comment by shivamsharma2710** [comment]
Hi @lachezartodorov 

Yes, documentation feedback has been taken into account, and we are working on improving it. As for the issue with `pushClickedPayloadReceived` not getting called on app launch in iOS, are you still experiencing this problem?

**Comment by shivamsharma2710** [comment]
@lachezartodorov, if you are still experiencing the `pushClickedPayloadReceived` issue in iOS, please create a separate ticket for it. 

Closing this ticket for now. Feel free to reach out, if you need further assistance.
