### ISSUE TITLE
Didn't Receive Push Notification

### ISSUE THREAD

**Issue by codxse** [CleverTap/clevertap-flutter#2]
Hi all,

Thank you for making such a plugin. Helping me a lot. I have question about push notification integration, especially for iOS platform. Well, I managed to integrate and push the FCMtoken to CleverTap dashboard. But I have an issue with receiving the notification, there was no notification at all, although it said "successfully sent".

I am following readme guide to integrate using `CleverTap.autoIntegrate()`.

```Swift
import UIKit
import Flutter
import flutter_downloader
import CleverTapSDK
import UserNotifications

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
      if #available(iOS 10.0, *) {
        UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
      }
    CleverTap.autoIntegrate()
    GeneratedPluginRegistrant.register(with: self)
    FlutterDownloaderPlugin.setPluginRegistrantCallback(registerPlugins)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

private func registerPlugins(registry: FlutterPluginRegistry) {
    //
    // Integration note:
    //
    // In Flutter, in order to work in background isolate, plugins need to register with
    // a special instance of `FlutterEngine` that serves for background execution only.
    // Hence, all (and only) plugins that require background execution feature need to
    // call `register` in this function.
    //
    // The default `GeneratedPluginRegistrant` will call `register` of all plugins integrated
    // in your application. Hence, if you are using `FlutterDownloaderPlugin` along with other
    // plugins that need UI manipulation, you should register `FlutterDownloaderPlugin` and any
    // 'background' plugins explicitly like this:
    //
    // FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "vn.hunghd.flutter_downloader"))
    //
    GeneratedPluginRegistrant.register(with: registry)
}
```

And I am initi the CleverTap on dart main function 

```Dart
...

    super.initState();
    _initPlatformState();
    cp.ClevertapPlugin.getInstance().activateCleverTapFlutterPluginHandlers();
    cp.CleverTapPlugin.setDebugLevel(3);
    cp.CleverTapPlugin.createNotificationChannelGroup("default-group", "Default Notification Group");
    cp.CleverTapPlugin.createNotificationChannel("default-channel", "Default Notification Channel", "YourChannelDescription", 3, true);
    cp.CleverTapPlugin.initializeInbox();

...

  void activateCleverTapFlutterPluginHandlers(){
    _clevertapPlugin = new CleverTapPlugin();
    _clevertapPlugin.setCleverTapInAppNotificationDismissedHandler(inAppNotificationDismissed);
    _clevertapPlugin.setCleverTapProfileDidInitializeHandler(profileDidInitialize);
    _clevertapPlugin.setCleverTapProfileSyncHandler(profileDidUpdate);
    _clevertapPlugin.setCleverTapInboxDidInitializeHandler(inboxDidInitialize);
    _clevertapPlugin.setCleverTapInboxMessagesDidUpdateHandler(inboxMessagesDidUpdate);
  }

...
```

Is there any configuration I missed? 

Thank you

**Comment by Aditi3** [comment]
Hi @codxse 

I see you are sending FCM Token to the CleverTap. FCM token is not supported on the iOS platform.
Could you send an APNS token and verify it again?

Also, you can implement our method to register for Push on iOS

` CleverTapPlugin.registerForPush();`

Helping link to our Example Application: https://github.com/CleverTap/clevertap-flutter/blob/master/example/lib/main.dart#L28

**Comment by codxse** [comment]
Thanks @Aditi3, I appreciate your answer.

Yes, It turn out that I have to push APNS token first. And I successfully send the notification message to the phone. :)

---

Here the code with `registerForPush();`

```Dart
    super.initState();
    _initPlatformState();
    cp.ClevertapPlugin.getInstance().activateCleverTapFlutterPluginHandlers();
    cp.CleverTapPlugin.setDebugLevel(3);
    cp.CleverTapPlugin.createNotificationChannelGroup("default-group", "Default Notification Group");
    cp.CleverTapPlugin.createNotificationChannel("default-channel", "Default Notification Channel", "YourChannelDescription", 3, true);
    cp.CleverTapPlugin.initializeInbox();
    log.i('registerFOrPush');
    cp.CleverTapPlugin.registerForPush();
    Future<String> initialUrl = cp.CleverTapPlugin.getInitialUrl();
    initialUrl.then((String url) { log.i('CleverTap initialUrl: $initialUrl'); });
```

----

Question again. But, how do I read custom key-value? is there any method or handler to read that?

**Comment by Aditi3** [comment]
Hi @codxse

Looks like you want to handle the push notifications payload and process the user's response to a notification.

Here is the link where you can find the answer to handle the notifications: 
https://stackoverflow.com/questions/55350391/cannot-read-payload-of-push-notification-sent-from-clevertap-dashboard/55361276#55361276

The link point to the React-Native SDK but the same solution can be implemented and should be functional in the Flutter SDK.

Hope this helps.

**Comment by bayuramadeza** [comment]
> Hi all,
> 
> Thank you for making such a plugin. Helping me a lot. I have question about push notification integration, especially for iOS platform. Well, I managed to integrate and push the FCMtoken to CleverTap dashboard. But I have an issue with receiving the notification, there was no notification at all, although it said "successfully sent".
> 
> I am following readme guide to integrate using `CleverTap.autoIntegrate()`.
> 
> ```swift
> import UIKit
> import Flutter
> import flutter_downloader
> import CleverTapSDK
> import UserNotifications
> 
> @UIApplicationMain
> @objc class AppDelegate: FlutterAppDelegate {
>   override func application(
>     _ application: UIApplication,
>     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
>   ) -> Bool {
>       if #available(iOS 10.0, *) {
>         UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
>       }
>     CleverTap.autoIntegrate()
>     GeneratedPluginRegistrant.register(with: self)
>     FlutterDownloaderPlugin.setPluginRegistrantCallback(registerPlugins)
>     return super.application(application, didFinishLaunchingWithOptions: launchOptions)
>   }
> }
> 
> private func registerPlugins(registry: FlutterPluginRegistry) {
>     //
>     // Integration note:
>     //
>     // In Flutter, in order to work in background isolate, plugins need to register with
>     // a special instance of `FlutterEngine` that serves for background execution only.
>     // Hence, all (and only) plugins that require background execution feature need to
>     // call `register` in this function.
>     //
>     // The default `GeneratedPluginRegistrant` will call `register` of all plugins integrated
>     // in your application. Hence, if you are using `FlutterDownloaderPlugin` along with other
>     // plugins that need UI manipulation, you should register `FlutterDownloaderPlugin` and any
>     // 'background' plugins explicitly like this:
>     //
>     // FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "vn.hunghd.flutter_downloader"))
>     //
>     GeneratedPluginRegistrant.register(with: registry)
> }
> ```
> 
> And I am initi the CleverTap on dart main function
> 
> ```dart
> ...
> 
>     super.initState();
>     _initPlatformState();
>     cp.ClevertapPlugin.getInstance().activateCleverTapFlutterPluginHandlers();
>     cp.CleverTapPlugin.setDebugLevel(3);
>     cp.CleverTapPlugin.createNotificationChannelGroup("default-group", "Default Notification Group");
>     cp.CleverTapPlugin.createNotificationChannel("default-channel", "Default Notification Channel", "YourChannelDescription", 3, true);
>     cp.CleverTapPlugin.initializeInbox();
> 
> ...
> 
>   void activateCleverTapFlutterPluginHandlers(){
>     _clevertapPlugin = new CleverTapPlugin();
>     _clevertapPlugin.setCleverTapInAppNotificationDismissedHandler(inAppNotificationDismissed);
>     _clevertapPlugin.setCleverTapProfileDidInitializeHandler(profileDidInitialize);
>     _clevertapPlugin.setCleverTapProfileSyncHandler(profileDidUpdate);
>     _clevertapPlugin.setCleverTapInboxDidInitializeHandler(inboxDidInitialize);
>     _clevertapPlugin.setCleverTapInboxMessagesDidUpdateHandler(inboxMessagesDidUpdate);
>   }
> 
> ...
> ```
> 
> Is there any configuration I missed?
> 
> Thank you

Can you share your example code for using clevertap. because i can't see data in my dashboart.
and  i go t a meesage "Somebody has invoked me to send the queue to CleverTap servers" ?

**Comment by darshanclevertap** [comment]
@bayuramadeza The repo contains an example project. Please check out the [main.dart](https://github.com/CleverTap/clevertap-flutter/blob/master/example/lib/main.dart) file

**Comment by darshanclevertap** [comment]
@codxse Is your issue resolved or is there something we can help you with? Please let us know

**Comment by bayuramadeza** [comment]
My issue has been closed, after i added region in manifest. Thanks

**Comment by Aditi3** [comment]
Hi @bayuramadeza 

Great to know it worked for you.

**Comment by Aditi3** [comment]
Hi @codxse 

I am going to close this issue here. If you need further help please feel free to email support at support@clevertap.com.

Thank you
