### ISSUE TITLE
Getting error when trying to record an event on flutter web 

### ISSUE THREAD

**Issue by eminsahinradity** [CleverTap/clevertap-flutter#210]
I got platform exception when trying to record an event on flutter web. Here is error stack trace. Are there any issue ? Could you please help

PlatformException(error, TypeError: Cannot read properties of undefined (reading 'event'), null, null)

══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
The following PlatformException was thrown:
PlatformException(error, TypeError: Cannot read properties of undefined (reading 'setLogLevel'),
null, null)
When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:49  throw_
packages/flutter/src/services/message_codecs.dart 652:7                       decodeEnvelope
packages/flutter/src/services/platform_channel.dart 310:18                    _invokeMethod
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
dart-sdk/lib/async/zone.dart 1407:47                                          _rootRunUnary
dart-sdk/lib/async/zone.dart 1308:19                                          runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                    handleValue
dart-sdk/lib/async/future_impl.dart 784:44                                    handleValueCallback
dart-sdk/lib/async/future_impl.dart 813:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 584:5                                     [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 657:7                                     <fn>
dart-sdk/lib/async/zone.dart 1399:13                                          _rootRun
dart-sdk/lib/async/zone.dart 1301:19                                          run
dart-sdk/lib/async/zone.dart 1209:7                                           runGuarded
dart-sdk/lib/async/zone.dart 1249:23                                          callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 177:15           <fn>

**Comment by KambleSonam** [comment]
Hello @eminsahinradity , 
Kindly add the below line in index.html 
  <script src="./assets/packages/clevertap_plugin/assets/clevertap.js"></script>

If the error still persist kindly revert.

**Comment by eminsahinradity** [comment]
Solved. Thank you very much. Please also add this information to documentation :)
