### ISSUE TITLE
com.clevertap.android.sdk.FcmMessageListenerService: java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by selvakumardreams** [CleverTap/clevertap-flutter#22]
10-16 16:35:18.248 25461 25461 E AndroidRuntime: FATAL EXCEPTION: main
10-16 16:35:18.248 25461 25461 E AndroidRuntime: Process: com.mapastory, PID: 25461
10-16 16:35:18.248 25461 25461 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate service com.clevertap.android.sdk.FcmMessageListenerService: java.lang.ClassNotFoundException: Didn't find class "com.clevertap.android.sdk.FcmMessageListenerService" on path: DexPathList[[zip file "/data/app/com.mapastory-1/base.apk"],nativeLibraryDirectories=[/data/app/com.mapastory-1/lib/arm64, /data/app/com.mapastory-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
10-16 16:35:18.248 25461 25461 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3234)
10-16 16:35:18.248 25461 25461 E AndroidRuntime:        at android.app.ActivityThread.-wrap5(ActivityThread.java)
10-16 16:35:18.248 25461 25461 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1615)
10-16 16:35:18.248 25461 25461 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
10-16 16:35:18.248 25461 25461 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:163)
10-16 16:35:18.248 25461 25461 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6238)
10-16 16:35:18.248 25461 25461 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-16 16:35:18.248 25461 25461 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
10-16 16:35:18.248 25461 25461 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
10-16 16:35:18.248 25461 25461 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.clevertap.android.sdk.FcmMessageListenerService" on path: DexPathList[[zip file "/data/app/com.mapastory-1/base.apk"],nativeLibraryDirectories=[/data/app/com.mapastory-1/lib/arm64, /data/app/com.mapastory-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
10-16 16:35:18.248 25461 25461 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-16 16:35:18.248 25461 25461 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
10-16 16:35:18.248 25461 25461 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
10-16 16:35:18.248 25461 25461 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3231)
10-16 16:35:18.248 25461 25461 E AndroidRuntime:        ... 8 more

**Comment by darshanclevertap** [comment]
@selvakumardreams If you have manually added the FcmMessageListenerClass in your app, please go through [this documentation for CleverTap Android SDK v4.0.0 changes.](https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTV4CHANGES.md)

**Comment by darshanclevertap** [comment]
@selvakumardreams Did your issue get resolved?

**Comment by gokrazee** [comment]
Yes its resolved

**Comment by selvakumardreams** [comment]
Thanks, its resolved.
