### ISSUE TITLE
Handling User Identity Reset and Event Recording Post-Logout

### ISSUE THREAD

**Issue by moo-kesh** [CleverTap/clevertap-flutter#226]
I would like to seek some guidance on a specific use case that involves user identity management. Our application requires the ability to reset the user identity upon logout and continue recording events under an anonymous profile until the user either logs back in or creates a new account. Here’s the scenario we are looking to support:

1. **User Logout:**When a user logs out of their account, we should reset their identity so that new events are not recorded under the logged-out account.
2. **Anonymous Event Recording:** Post-logout, any events triggered should be recorded under an anonymous profile.
3. **Re-Identification:** Upon login or account creation, we want to re-identify the user and merge the events recorded anonymously with their new profile.

**Comment by Anush-Shand** [comment]
@moo-kesh Currently we don't have any explicit logout functionality. 
The way the above use-case can be achieved is by clearing the Clevertap specific cache on logout. This will address all the 3 points mentioned

**Comment by Anush-Shand** [comment]
@moo-kesh Closing this issue. For further clarification and assistance you can connect with the clevertap support team [via this link](https://help.clevertap.com/hc/en-us)
