### ISSUE TITLE
issue in IOS while initializing in main function.

### ISSUE THREAD

**Issue by pankajunivest1** [CleverTap/clevertap-flutter#240]
The 'clevertap_plugin/native_to_dart' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.

**Comment by shivamsharma2710** [comment]
Hi @pankajunivest1,

Thank you for reporting this issue. To help us investigate further, could you please provide the following details:

1. Which CleverTap Plugin version are you facing this issue with?
2. What code of the Plugin are you using in the main function?
3. Are you getting any `PlatformException` from the Plugin, if not then please specify what issue you're facing with iOS?

**Comment by pankajunivest1** [comment]
1. currently using latest version : clevertap_plugin: ^2.4.0
2. CleverTapPlugin.createNotificationChannelWithSound();CleverTapPlugin.
registerForPush().then((value) {});CleverTapPlugin.enablePersonalization()
*;*
3. currently i facing this error
(The 'clevertap_plugin/native_to_dart' channel sent a message from native
to Flutter on a non-platform thread. Platform channel messages must be sent
on the platform thread. Failure to do so may result in data loss or
crashes, and must be fixed in the plugin or application code creating that
channel.)
this is crashing my ios build in android it is working very fine

**Comment by nishant-clevertap** [comment]
Hi @pankajunivest1,
Thanks for reporting the issue, we are working on this. We will update you when new version will be released with the fix.

**Comment by pankajunivest1** [comment]
sure, we are eagerly waiting for this update.

**Comment by abhinand-kv** [comment]
Any update on this

**Comment by dhanasonmo** [comment]
any update on this?

**Comment by amol-d** [comment]
Any update on this?

**Comment by nishant-clevertap** [comment]
The fix for this has been released on our latest v2.4.1. Please update to our latest version: https://github.com/CleverTap/clevertap-flutter/releases/tag/2.4.1
