### ISSUE TITLE
It is possible to call a hideInbox() or something else, i want to dismiss inbox page.

### ISSUE THREAD

**Issue by danilopena** [CleverTap/clevertap-flutter#25]
Hello everyone!

We are using Inbox feature to send some images/links and deeplinks. But in iOS when users click on banner, my deeplink page open behind the Inbox, so i want to force 'dissmis' when i receive deeplinks.

I cant find how to do this.

**Comment by Aditi3** [comment]
Hi @danilopena 

Currently, our SDK doesn't have any public API to hide the App Inbox. I will take this up for discussion with our engineering team and keep you updated here if we can consider providing `hideInbox` public API to dismiss the App Inbox Controller.

Thank you!

**Comment by Aditi3** [comment]
Closing this as it is being taken up by Support.

**Comment by boymustafa** [comment]
hi @Aditi3 
is there any news about this issue? I face the same issue here.
