### ISSUE TITLE
deprecated CleverTapPlugin.fetchAndActivate() -> version clevertap_plugin: 2.4.0

### ISSUE THREAD

**Issue by tomkawohl** [CleverTap/clevertap-flutter#254]
Hi,

I upgraded clevertap_plugin to 2.4.0. I see that `CleverTapPlugin.fetchAndActivate()` is deprecated. However, the documentation is not updated and i can't find replacement to it. `fetch` and `activate` are of course deprecated too. 
The documentation where fetch and activate are deprecated but still used: https://developer.clevertap.com/docs/flutter-advanced-features
In the example given in your git, it is also fetch and activate that are used.

What could i do to replace it please ?

Have a nice day.

**Comment by Anush-Shand** [comment]
@tomkawohl 
Thanks for raising this query

`CleverTapPlugin.fetchAndActivate()`, `activate()`, `fetchWithMinimumIntervalInSeconds()` and other such functions related to `ProductConfig` feature has been deprecated in lieu of an upgraded and revamped feature. 
This is currently in private beta and will be GA'd soon. If you wish to enroll to the private beta of the new Product Experiences then you can connect with the Clevertap team.

Having said this, even though these methods are deprecated, they can still be used if you want to keep using the old Product Config

**Comment by tomkawohl** [comment]
Thanks for your response
