### ISSUE TITLE
Notification Works for Flutter ( Android )?

### ISSUE THREAD

**Issue by jaspreet1990** [CleverTap/clevertap-flutter#28]
As I have seen 
https://github.com/CleverTap/clevertap-flutter/blob/5cc3021c04f1a5bee4d9ef1763e6d4b42d9eed47/example/lib/main.dart#L32 
 
**CleverTapPlugin.registerForPush()**; //only for iOS
There is comment that Only for IOS

**Comment by darshanclevertap** [comment]
Duplicate of #29 Closing this
