### ISSUE TITLE
Notification Works for Fluter ( Android ) ?

### ISSUE THREAD

**Issue by jaspreet1990** [CleverTap/clevertap-flutter#29]
As I have seen 
https://github.com/CleverTap/clevertap-flutter/blob/5cc3021c04f1a5bee4d9ef1763e6d4b42d9eed47/example/lib/main.dart#L32 
 
**CleverTapPlugin.registerForPush()**; //only for iOS
There is comment that Only for IOS

**Comment by jaspreet1990** [comment]
@darshanclevertap  , Any help on this ?

**Comment by darshanclevertap** [comment]
@jaspreet1990 Sorry for the delay. Our SDK supports Push Notifications for both Android and iOS. You can check out CleverTap documentation for Push notifications in [Android here](https://developer.clevertap.com/docs/android#section-push-notifications) and [iOS here](https://developer.clevertap.com/docs/ios#section-push-notifications). Or else you can use the Firebase plugin for Flutter
