### ISSUE TITLE
invoked me to send the queue to CleverTap servers

### ISSUE THREAD

**Issue by bayuramadeza** [CleverTap/clevertap-flutter#3]
Hi, i tried to send profile information to clevertap.
The query is running  but the response is empty. 
I have add account id and account token in manifest

This is the response 

> D/CleverTap:TEST-7R4-K6W-Z85Z(10433): Send queue contains 1 items: [{"g":"__gb6354d8ef5b3466c897414ae0159962a","type":"meta","af":{"Build":"1","Version":"1.0.0","OS Version":"9","SDK Version":30603,"Make":"samsung","Model":"SM-A730F","Carrier":"","useIP":false,"OS":"Android","wdt":2.64,"hgt":5.43,"dpi":420,"lib":"Flutter"},"id":"TEST-7R4-K6W-Z85Z","tk":"TEST-063-42a","l_ts":1582096169,"f_ts":1582002710,"ddnd":false,"rtl":[],"ref":{"us":"google-play","um":"organic"},"imp":0,"tlc":[]}, {"profile":{"Email":"devtest17@gmail.com","Education":"Graduate","Phone":"+628123456789","Gender":"M","Identity":"15711750215d215cf8597fc","Age":"","Name":"Dev","Location":"","tz":"Asia\/Jakarta"},"s":1582096167,"pg":1,"type":"profile","ep":1582097144,"f":false,"lsl":-197,"dsync":true}]
  V/CleverTap: Getting domain from header - null
  V/CleverTap: Inbox: Processing response
  V/CleverTap: Inbox: Response JSON object doesn't contain the inbox key
  V/CleverTap: Processing Display Unit items...
  V/CleverTap: DisplayUnit : JSON object doesn't contain the Display Units key
  D/CleverTap: Queue sent successfully
  V/CleverTap: Returning Queued events
  V/CleverTap: No events in the queue, bailing
  V/CleverTap: Pushing Notification Viewed event onto queue flush sync
  V/CleverTap: Pushing Notification Viewed event onto queue DB flush
  V/CleverTap: Somebody has invoked me to send the queue to CleverTap servers
  V/CleverTap: Returning Queued Notification Viewed events
  V/CleverTap: No events in the queue, bailing

**Comment by darshanclevertap** [comment]
@bayuramadeza As far as I understand, these logs denote that profile information has been sent. Could you please go to our dashboard, on the left nav bar, you will see "Find People", put in the email address you passed in the profile info and check if the profile exists.

**Comment by bayuramadeza** [comment]
it works now, after i added region in manifest. thanks

**Comment by ParagSDeshpande09** [comment]
> 

Can you tell me what did you add in manifest to make it work please?
