### ISSUE TITLE
Null Pointer exception (if app is closed, has deeplink) and using build from fix for 

### ISSUE THREAD

**Issue by gouravd** [CleverTap/clevertap-flutter#30]
I was running into the issue - https://github.com/CleverTap/clevertap-flutter/issues

I saw the fix already in branch - https://github.com/CleverTap/clevertap-flutter/tree/task/release/SDK-540

So for testing I did overriding in pubsec.yaml. The issue seems to be resolved. However if thee Push notification has deeplink and app is closed, clicking on the push notification crashes app while app launches. This is the stack

E/AndroidRuntime(31896): java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
E/AndroidRuntime(31896): 	at com.clevertap.clevertap_plugin.CleverTapPlugin.lambda$invokeMethodOnUiThread$1(CleverTapPlugin.java:1109)
E/AndroidRuntime(31896): 	at com.clevertap.clevertap_plugin.-$$Lambda$CleverTapPlugin$dCL-qXjpvRMhyuAXGDEKOp5Wxtg.run(Unknown Source:6)
E/AndroidRuntime(31896): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(31896): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(31896): 	at android.os.Looper.loop(Looper.java:201)
E/AndroidRuntime(31896): 	at android.app.ActivityThread.main(ActivityThread.java:6810)
E/AndroidRuntime(31896): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31896): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime(31896): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

On android Tested with Clevertap is 4.0.0 and 4.0.1

[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on macOS 11.1 20C69 darwin-x64, locale en-IN)
    • Flutter version 1.25.0-8.1.pre at /Users/gouravd/development/flutter
    • Framework revision 8f89f6505b (4 weeks ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/gouravd/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/gouravd/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

**Comment by darshanclevertap** [comment]
@gouravd The code in this [branch](https://github.com/CleverTap/clevertap-flutter/tree/task/release/SDK-540) is unreleased. How did you override your `pubspec.yaml` to check this code?

**Comment by darshanclevertap** [comment]
@gouravd this will finally be release in the next version due release on Friday

**Comment by darshanclevertap** [comment]
This has been fixed in CT Flutter Plugin v1.2.2
