### ISSUE TITLE
class file for com.clevertap.android.sdk.SyncListener not found

### ISSUE THREAD

**Issue by aamirzaidi** [CleverTap/clevertap-flutter#32]
Using Flutter SDK.
First time installing cleverTap 

I have followed all the steps listed in clevertap_plugin at  pub.dart. 
(Steps I have done for clarification ): 

1.  install dependency from pub.dart.
2. Added the code to my dependencies section in project/build.gradle.
3. Add the code to my dependencies section in app/build.gradle
4. At the end of the app/build.gradle file added the code provided in the step.
5. **NEXT STEP : In your app's Android Application class add the following code. (Since i didn't have an Application class, i added this in AndroidManifest.xml as advised in the next step)** 
`    <application
        android:label="@string/app_name"
        android:icon="@drawable/ic_launcher"
        android:name="com.clevertap.android.sdk.Application"> 
` 

6. Added the permissions which are needed by the CleverTap SDK.
7. Added my CleverTap Project ID and Token to my AndroidManifest.xml, within the tags.

However, i am still seeing the following error. I was using previous version of flutter and i upgraded it, also tried several channels but the issue doesn't go away.
Am i missing something. Plz Help Clevertap with this issue.
![Screenshot 2021-02-10 154700](https://user-images.githubusercontent.com/58393469/107496542-715c6580-6bb7-11eb-9ddd-de2f05a1d109.jpg)

**Comment by aamirzaidi** [comment]
@darshanclevertap

**Comment by darshanclevertap** [comment]
@aamirzaidi 
Which version of CleverTap Flutter did you add in `pubspec.yaml`? And which version of the CleverTap Android SDK did you add in the `build.gradle`?

**Comment by aamirzaidi** [comment]
@darshanclevertap 
**In `pubsec.yaml` I added `clevertap_plugin: ^1.2.0`.**
**And in my `app\build.gradle` i added this line of code (as advised from the [plugin page](https://pub.dev/packages/clevertap_plugin) ) :**  

        //For CleverTap Android SDK v3.6.4 and above add the following -
        implementation 'com.android.installreferrer:installreferrer:2.1'

**Comment by aamirzaidi** [comment]
It's solved by adding the line `implementation 'com.clevertap.android:clevertap-android-sdk:3.8.2'`
You somehow didn't added this line in your steps listed on the [plugin page](https://pub.dev/packages/clevertap_plugin).

**Comment by darshanclevertap** [comment]
@aamirzaidi I'd suggest you update to `implementation 'com.clevertap.android:clevertap-android-sdk:4.0.0'`
We will add this in our documentation
