### ISSUE TITLE
Navigate to a screen with custom key value pairs.

### ISSUE THREAD

**Issue by amgugu111** [CleverTap/clevertap-flutter#35]
This is where I activate the handler:

_clevertapPlugin.setCleverTapPushClickedPayloadReceivedHandler(pushClickedPayloadReceived);

This is the method I call:

pushClickedPayloadReceived(Map<String, dynamic> map) {
    var route = ''; 
    route = map["route"];
    switch (route) {
      case '/profile':
        scheduleMicrotask(() {
          return Navigator.pushReplacementNamed(context, '/profile');
        });
        break;
      case '/wallet':
        scheduleMicrotask(() {
          return Navigator.pushNamed(context, '/wallet');
        });
        break;
      default:
    }
  }

It doesn't work. Please help me with this @darshanclevertap @Aditi3 @piyush-kukadiya @ygit

**Comment by amgugu111** [comment]
Closing the issue, fixed it.

**Comment by epynic** [comment]
How was this fixed @amgugu111 ?
