### ISSUE TITLE
Firebase.onmessaging conflict with clevertap listener

### ISSUE THREAD

**Issue by bayuramadeza** [CleverTap/clevertap-flutter#4]
Hi, clevertap team. Thanks for your work on this clevertap plugin for flutter. 
But, i have a problem with firebasemessaging onmessage method. the method doesn't work anymore after i added 
"com.clevertap.android.sdk.FcmTokenListenerService" 
and 
"com.clevertap.android.sdk.FcmMessageListenerService". in my manifest
So what should i do? i need to handle notification from firebase too.

**Comment by darshanclevertap** [comment]
@bayuramadeza 
In our latest release, v1.1.0, I have added a `createNotification` method. You can remove the `FcmTokenListenerService` and `FcmMessageListenerService`. 
To pass the FCM token to us, you can use the `setPushToken ` method and pass the token to us as a String.
To handle the notification via CleverTap, in the `onMessageReceived` of Firebase, extract the data using the `message.getData` and pass it to the `createNotification` method of CleverTap Flutter Plugin.

**NOTE** - `createNotification` method is only for Android

**Comment by bayuramadeza** [comment]
@darshanclevertap i have implemented setPushToken in my apps.
When i tried to push notification from clevertap dashboard, i got new issue. Notification doesn't trigger in onbackground and onlaunch because of notification body and title were null. 
this is the response.
If notification(title and body were not null) everything's fine

> {notification: {title: null, body: null}, data: {wzrk_acct_id: TEST-7R4-K6W-Z85Z, id_notif: 1234, nm: test, nt: test, pr: high, wzrk_pivot: wzrk_default, wzrk_rnv: false, wzrk_ttl: 1582969106, wzrk_push_amp: false, wzrk_bc: , wzrk_bi: 2, wzrk_id: 0_0, wzrk_pn: true}}

**Comment by darshanclevertap** [comment]
@bayuramadeza This is because of Firebase. They don't trigger onBackground and onLaunch when the Push contains only data object. Could you please try and raise the issue with them?
