### ISSUE TITLE
Null Safety and Web support

### ISSUE THREAD

**Issue by robbin7ramos** [CleverTap/clevertap-flutter#41]
please add support to null safety and also as flutter web now added to the stable channel, its also better to support it.
Thanks thanks

**Comment by saswatsaubhagya** [comment]
When can we expect the same ??

**Comment by darshanclevertap** [comment]
@saswatsaubhagya @robbin7ramos We're working on updating our Flutter plugin to 2.0 for null safety first. I'll be able to share release timelines with you in a few days. As for Web support, we're still a long way away as we do not have the base for web support ready in this plugin, but nonetheless, we'll take this into consideration soon.

**Comment by darshanclevertap** [comment]
@saswatsaubhagya @robbin7ramos We'll be supporting Flutter v2.2 and null safety in the upcoming release due on Friday

**Comment by darshanclevertap** [comment]
Null Safety has been added in CT Flutter Plugin v1.2.2
