### ISSUE TITLE
MissingPluginException when call CleverTapPlugin.setPushToken(token)

### ISSUE THREAD

**Issue by aldychris** [CleverTap/clevertap-flutter#42]
It's throw me Exception when trying setPushToken on iOS(Simulator) by use this function

`CleverTapPlugin.setPushToken(token)`

`{MissingPluginException(No implementation found for method setPushToken on channel clevertap_plugin)}`

On iOS I only can found that related to set PushToken
`if ([@"setPushTokenAsString" isEqualToString:call.method])`

but I can't find function to call that function in [here](https://github.com/CleverTap/clevertap-flutter/blob/master/lib/clevertap_plugin.dart)

**Comment by Aditi3** [comment]
Thank you @aldychris  for reporting to us. Please allow me some time to re-check the same at my end and I will get back to you with an update shortly. 

Meanwhile, could you try using `registerForPush` method for enabling push notification support on the iOS platform.

Example usage for the same can be found [here](https://github.com/CleverTap/clevertap-flutter/blob/master/example/lib/main.dart#L32).

**Comment by Aditi3** [comment]
Yes,`registerForPush` and the aforementioned code snippet will resolve the issue for you.
