### ISSUE TITLE
In-App Messages shows up as notification

### ISSUE THREAD

**Issue by epynic** [CleverTap/clevertap-flutter#44]
Have created an Campaign in CleverTap - Mobile In-app, Single Message
And as per the campaign preview we expect to see a pop up modal with the message,

![image](https://user-images.githubusercontent.com/2527481/118436342-49bcf200-b6fe-11eb-8a28-a2054fd55890.png)

While testing the campaign, we receive a Notification instead
![image](https://user-images.githubusercontent.com/2527481/118436103-cdc2aa00-b6fd-11eb-8d27-e0778760af53.png)

The debug message in console is as below
![image](https://user-images.githubusercontent.com/2527481/118436567-a9b39880-b6fe-11eb-83a5-6cb392b825dc.png)

**Comment by william-ct** [comment]
Hi @epynic , campaigns which are being tested for in-app messages work as expected as above.However, live campaigns will render the in-app notifications as an in-app message rather than a notification.Thanks!

**Comment by epynic** [comment]
@william-ct  It is the same console error for live campaigns, are we missing something ?

![image](https://user-images.githubusercontent.com/2527481/118446951-d15e2d00-b70d-11eb-850c-3088d0e6b584.png)

This is on Android using the latest clevertap plugin

**Comment by william-ct** [comment]
Hi @epynic what's the superclass of your MainActivity?

**Comment by epynic** [comment]
@william-ct 
The MainActivity file
![image](https://user-images.githubusercontent.com/2527481/118483017-22344c80-b733-11eb-99dc-a266dce6fee1.png)

AndroidManifest.xml
![image](https://user-images.githubusercontent.com/2527481/118483123-48f28300-b733-11eb-85d8-23ce69ef423b.png)

**Comment by darshanclevertap** [comment]
@epynic Our Header and Footer InApp templates in Android are Fragments. Now Fragments are only allowed to be created on Activities that extend FragmentActivity or AppCompatActivity. Meanwhile, the base Activity of any Flutter app is FlutterActivity. 

FlutterActivity does not extend either of them and hence because of this technical issue, Header and Footer InApp templates will currently not work on Android via the CleverTap Flutter Plugin. 

Now I know this is an inconvenience for our Flutter devs, but I assure you we have started working on providing a fix for the same, unfortunately, this fix will have to be made in the CleverTap Android SDK first and then shipped into the Flutter Plugin. 

For the time being you can run Header/Footer InApp templates on your iOS devices or use any of our other InApp templates. I'll be marking this issue as an enhancement on our side and will provide proper timelines for this in the coming week.

I'd like to thank you for your patience while we fix this as soon as possible.

**Comment by epynic** [comment]
@darshanclevertap thank you for acknowledging , waiting for the fix!

**Comment by darshanclevertap** [comment]
@epynic There is a workaround if you wish to try, you can extend your App's MainActivity from FlutterFragmentActivity instead of FlutterActivity. This will have almost no side effects on your app and it will ensure CleverTap's Header & Footer InApp templates can be used by your app. Please try it once and let us know if it works for you.

**Comment by darshanclevertap** [comment]
@epynic Did you try the workaround? You can check out the [MainActivity](https://github.com/CleverTap/clevertap-flutter/blob/master/example/android/app/src/main/java/com/example/clevertap_plugin_example/MainActivity.java) of the example project for reference

**Comment by epynic** [comment]
@darshanclevertap - worked like a charm! Thanks :)

is there a way to handle custom key-value pair data on Button clicks ?

**Comment by darshanclevertap** [comment]
@epynic Do you mean button click of the InApp notification?

**Comment by epynic** [comment]
> @epynic Do you mean button click of the InApp notification?

Yes, the custom key-value pair data

![image](https://user-images.githubusercontent.com/2527481/119334262-86618e00-bca8-11eb-829b-3423f322047e.png)

**Comment by darshanclevertap** [comment]
@epynic Have you implemented the `setCleverTapInAppNotificationButtonClickedHandler ` as shown [here](https://github.com/CleverTap/clevertap-flutter/blob/master/example/lib/main.dart#L57)?

**Comment by epynic** [comment]
@darshanclevertap 

Using the custom render in the manifest files
```
<service
        android:name="com.clevertap.android.sdk.pushnotification.fcm.FcmMessageListenerService">
        <intent-filter>
            <action android:name="com.google.firebase.MESSAGING_EVENT"/>
        </intent-filter>
    </service>
```

we are able to receive the InApp messagings and Push notifications, while sending custom key-pair value data is not reflected in  `setCleverTapPushClickedPayloadReceivedHandler` or `setCleverTapInAppNotificationButtonClickedHandler`

Is there anything we am missing out ?

**Comment by darshanclevertap** [comment]
@epynic No, this should be it. Are you testing it on an emulator or a device? If you're using a device, can you disable battery optimizations for your app and test it once?

**Comment by epynic** [comment]
@darshanclevertap 

the minimal [main.dart](https://gist.github.com/epynic/297e531c3d98f86d3b3c352bad245d4f#file-main-dart)

This is on android physical device there is no battery optimisations enabled.

Log when the Push Notification is sent

![Screenshot 2021-05-25 at 5 18 19 PM](https://user-images.githubusercontent.com/2527481/119494066-8469fe80-bd7e-11eb-9f8c-8d953e4fd068.png)


On notification click.
![Screenshot 2021-05-25 at 5 20 51 PM](https://user-images.githubusercontent.com/2527481/119494143-99469200-bd7e-11eb-9d33-e4270e4bef6e.png)

We are able to send receive notification & in-app messaging, only issue is we are unable to handle the custom key-pair values.

**Comment by epynic** [comment]
@darshanclevertap  - help ?

**Comment by darshanclevertap** [comment]
@epynic Sorry for the delay. Can you try calling `activateCleverTapFlutterPluginHandlers` inside `_firebaseMessagingBackgroundHandler`? My guess is that the `setCleverTapPushClickedPayloadReceivedHandler` is not set when the App Launches after clicking a notification. This causes the `Notification Clicked` event to be raised as per the logs but there is no callback to the dart file.

**Comment by epynic** [comment]
@darshanclevertap  is the same behaviour,setCleverTapPushClickedPayloadReceivedHandler or setCleverTapInAppNotificationButtonClickedHandler are not triggered.

The only was we could get this working is by removing the firebase cloud messaging plugin.
But this is not the intended behaviour we are look for - we would need firebase cloud-messaging to work along side with clevertap.

**Comment by darshanclevertap** [comment]
@epynic We will be working on ensuring that Firebase cloud messaging and the CleverTap Flutter plugin do work together seamlessly but for now, this is the only way we have.

Closing this for now.
