### ISSUE TITLE
Push notification title and body null which results in notification not being rendered while app is in Background OR Closed

### ISSUE THREAD

**Issue by yashpalzala** [CleverTap/clevertap-flutter#46]
I'm trying to implement push notifications from Clevertap on my android device.
I'm getting the push notification but the title and body of the notification is null and thus android does not show the notification.
![cltap-notif](https://user-images.githubusercontent.com/54407840/118799147-07411400-b8bc-11eb-9fe7-4710f83ba908.jpg)

So how do I send title and body ??

**Comment by darshanclevertap** [comment]
@yashpalzala CleverTap Push notification payload is sent in the data object of the FCM Push. Are you trying to custom render the Push Notifications? Have you added the `FcmMessageListenerService` class in your `AndroidManifest.xml`?

**Comment by yashpalzala** [comment]
> @yashpalzala CleverTap Push notification payload is sent in the data object of the FCM Push. Are you trying to custom render the Push Notifications? Have you added the `FcmMessageListenerService` class in your `AndroidManifest.xml`?

Yes, I added FcmMessageListenerService but after adding this service fcm's onMessage, onLaunch , onResume are not executing so I had to remove the FcmMessageListenerService  
![cltap-git](https://user-images.githubusercontent.com/54407840/118813698-09f83500-b8cd-11eb-83e0-5ff3aabac289.jpg)

**Comment by yashpalzala** [comment]
> @yashpalzala CleverTap Push notification payload is sent in the data object of the FCM Push. Are you trying to custom render the Push Notifications? Have you added the `FcmMessageListenerService` class in your `AndroidManifest.xml`?

And anyways android does not show notifications if the title and body is null , right ?

**Comment by darshanclevertap** [comment]
@yashpalzala if you're using FCM's `onMessage`, `onLaunch` , `onResume`, I'd suggest you extract the data object from the CleverTap Push Notification payload and call the method `createNotification` provided by the CleverTap Flutter Plugin to render the push notifications

**Comment by yashpalzala** [comment]
Yes but that is when app is in foreground . What about when app is in
background OR closed . How can I show notification then ?

**Comment by darshanclevertap** [comment]
FCM provides the `onBackgroundMessage` method as well. You can call the same `createNotification` CleverTap method in that method

**Comment by epynic** [comment]
> FCM provides the `onBackgroundMessage` method as well. You can call the same `createNotification` CleverTap method in that method

using `createNotification` how can get the custom data(key-value) sent from clevertap ?

**Comment by yashpalzala** [comment]
> > FCM provides the `onBackgroundMessage` method as well. You can call the same `createNotification` CleverTap method in that method
> > @darshanclevertap
> > using `createNotification` how can get the custom data(key-value) sent from clevertap ?

@epynic createNotification is to render the notification 
if you want to access data then you can do message[data].
So the whole structure would be like , 
 onMessage: (var message) async {
        fcm = Fcm.fromJson(message);
        print("CleverTap Push notif ---- $message");
        CleverTapPlugin.createNotification(jsonEncode(message['data']));
        }

**Comment by darshanclevertap** [comment]
@yashpalzala As per [FCM Flutter docs for Background Messages](https://firebase.flutter.dev/docs/messaging/usage/#background-messages) you can implement the global method `_firebaseMessagingBackgroundHandler ` and in that method you can call the `createNotification` of CleverTap

**Comment by epynic** [comment]
@yashpalzala @darshanclevertap , agreed in `onBackgroundMessage`  / `_firebaseMessagingBackgroundHandler`  we can use `CleverTapPlugin.createNotification()` to create the notification. ( when the app is closed/background)

suppose when we tap/open the notification created by clevertap, we would like to  route to a specific page based on the custom data (key value) - how can we  get the custom data(key-value) here ?

`FirebaseMessaging.onMessageOpenedApp` does not work as this notification was created by clevertap.

**Comment by yashpalzala** [comment]
> @yashpalzala As per [FCM Flutter docs for Background Messages](https://firebase.flutter.dev/docs/messaging/usage/#background-messages) you can implement the global method `_firebaseMessagingBackgroundHandler` and in that method you can call the `createNotification` of CleverTap

Ok I got your point @darshanclevertap  .
But if you read this line it states  --- Once displayed, the background handler will be executed (if provided).
in the documentation https://firebase.flutter.dev/docs/messaging/usage/#notifications

So this means that onBackgroundMessage() only executes if the notification is being displayed , but if the notification has title and body null then notification is not going to be displayed . 

Please correct me if I'm missing something @darshanclevertap .

**Comment by yashpalzala** [comment]
> @yashpalzala @darshanclevertap , agreed in `onBackgroundMessage` / `_firebaseMessagingBackgroundHandler` we can use `CleverTapPlugin.createNotification()` to create the notification. ( when the app is closed/background)
> 
> suppose when we tap/open the notification created by clevertap, we would like to route to a specific page based on the custom data (key value) - how can we get the custom data(key-value) here ?
> 
> `FirebaseMessaging.onMessageOpenedApp` does not work as this notification was created by clevertap.

@epynic  Have you tried this (onBackgroundMessage) method to get notification when the app is closed can you please share an example .

@epynic message is a map so you can get any custom value by doing var myCustomValue = message['data']['myCustomDataKey'] and then navigate user accordingly

**Comment by epynic** [comment]
> @epynic message is a map so you can get any custom value by doing var myCustomValue = message['data']['myCustomDataKey'] and then navigate user accordingly

you use `CleverTapPlugin.createNotification()` to create notification, now when you click on the notification you need to route the user to the page, and there is no way to get custom value in flutter.

There is a closed issue https://github.com/CleverTap/clevertap-flutter/issues/13 that mentions the same use case, and to fix this we need to use custom-listeners, and this custom-listeners is custom for android & ios, so out of box this does not work i suppose.

**Comment by darshanclevertap** [comment]
> you use CleverTapPlugin.createNotification() to create notification, now when you click on the notification you need to route the user to the page, and there is no way to get custom value in flutter.

@epynic You can get the custom value after clicking the notification using the `setCleverTapPushClickedPayloadReceivedHandler`. This will give you the entire Push Notification payload as sent from CleverTap in the form of a Map.

**Comment by darshanclevertap** [comment]
@yashpalzala I did read that, but under the [Message Types](https://firebase.flutter.dev/docs/messaging/usage/#message-types) section, they say that to handle Data messages in the Terminated state, you can use the `onBackgroundMessage` as well. Could you please try it out once? If you face issues, we will try to help you resolve them. 😇

**Comment by yashpalzala** [comment]
> @yashpalzala I did read that, but under the [Message Types](https://firebase.flutter.dev/docs/messaging/usage/#message-types) section, they say that to handle Data messages in the Terminated state, you can use the `onBackgroundMessage` as well. Could you please try it out once? If you face issues, we will try to help you resolve them. 😇

@darshanclevertap Ok I did as you suggested.

While in the background I'm able to get the data from the payload but create notification seems to be missing plugin implementation which is unexpected as I have implemeted clevertap SDK ---

implementation 'com.clevertap.android:clevertap-android-sdk:4.0.0'

![image](https://user-images.githubusercontent.com/54407840/118960079-8b5ccf80-b980-11eb-841f-ab36ea4fb5c2.png)

AND When the app is in background I get --
E/FirebaseInstanceId(32509): Error while delivering the message: ServiceIntent not found.

![image](https://user-images.githubusercontent.com/54407840/118960469-f3131a80-b980-11eb-8127-aca8b5c58c54.png)

Here's my andoid manifest file - 

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.pnjaa.twinein">
    
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_CONTACTS"/>
    
    <application
    
        android:label="TwineIn"
        android:icon="@drawable/app_icon"
        android:requestLegacyExternalStorage="true"
        android:allowBackup="false" 
        android:name=".Application"
        >
        
        

    <meta-data
    android:name="CLEVERTAP_NOTIFICATION_ICON"
    android:value="ic_stat_name"/> 
        
        
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/ic_stat_name" />
        
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_color"
            android:resource="@color/colorPrimary" />
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTask"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
                android:name="flutterEmbedding"
                android:value="2" />
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>

            
            <intent-filter>
                <data android:scheme="twinein" />
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>

            
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https" android:host="v7gm2.app.link" />
                
                <data android:scheme="https" android:host="v7gm2-alternate.app.link" />
            </intent-filter>

        </activity>

        <meta-data android:name="com.facebook.sdk.ApplicationId" 
        android:value="@string/facebook_app_id"/>
    
        <activity android:name="com.facebook.FacebookActivity"
            android:configChanges=
                    "keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label="@string/app_name" />
        <activity
            android:name="com.facebook.CustomTabActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/fb_login_protocol_scheme" />
            </intent-filter>
        </activity>
        <activity
            android:name="com.yalantis.ucrop.UCropActivity"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar"/>
        


        
        <meta-data android:name="io.branch.sdk.BranchKey" android:value="key_live_************************" />
        <meta-data android:name="io.branch.sdk.BranchKey.test" android:value="key_test_********************" />
        <meta-data android:name="io.branch.sdk.TestMode" android:value="${branch}" />     

        

        
        <meta-data
        android:name="CLEVERTAP_ACCOUNT_ID"
        android:value="TEST-***-***-****"/>
        <meta-data
        android:name="CLEVERTAP_TOKEN"
        android:value="TEST-***-***"/>

    </application>
</manifest>`

And app/build.gradle ( dependencies ) -- 
`dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:support-annotations:28.0.0'
    implementation 'com.google.firebase:firebase-messaging:20.2.4' // do I need to change to 17.3.4 
    implementation 'com.google.firebase:firebase-messaging-ktx'
    //=========== from cleverTap SDK ========================//
    implementation 'androidx.core:core:1.3.0'
    implementation 'androidx.fragment:fragment:1.1.0'
    implementation 'com.android.support:multidex:2.0.1'
    implementation 'androidx.browser:browser:1.2.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'com.facebook.android:facebook-android-sdk:[5,6)'
    implementation 'com.facebook.android:facebook-core:[4,5)'
    implementation 'com.facebook.android:facebook-marketing:[4,5)'


    //================================ CLEVERTAP================================//
    implementation 'com.clevertap.android:clevertap-android-sdk:4.0.0'
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.android.support:appcompat-v7:28.0.0'//MANDATORY for App Inbox
    implementation 'com.android.support:design:28.0.0'//MANDATORY for App Inbox
    implementation 'com.github.bumptech.glide:glide:4.9.0'//MANDATORY for App Inbox
    implementation 'androidx.recyclerview:recyclerview:1.1.0'
    implementation 'androidx.viewpager:viewpager:1.0.0'
    implementation 'com.google.android.material:material:1.2.1'
    //For CleverTap Android SDK v3.6.4 and above add the following -
    implementation 'com.android.installreferrer:installreferrer:1.0'
    implementation 'com.google.android.gms:play-services-mlkit-image-labeling:16.0.0'
    implementation 'com.google.android.gms:play-services-mlkit-face-detection:16.1.1'
}`

**Comment by epynic** [comment]
> E/FirebaseInstanceId(32509): Error while delivering the message: ServiceIntent not found.

Can you check if notifications sent from firebase cloud messaging work ?

**Comment by darshanclevertap** [comment]
@yashpalzala [This flutter issue](https://github.com/flutter/flutter/issues/28000#issuecomment-471004309) says that you need to delete the build folder and relaunch the app

**Comment by yashpalzala** [comment]
> @yashpalzala [This flutter issue](https://github.com/flutter/flutter/issues/28000#issuecomment-471004309) says that you need to delete the build folder and relaunch the app

@darshanclevertap As you uggested I deleted the build folder and relaunched the app and still the error persists 


![image](https://user-images.githubusercontent.com/54407840/119034985-b1a85c80-b9cc-11eb-8c6d-d69b20766eac.png)

![image](https://user-images.githubusercontent.com/54407840/119035054-c71d8680-b9cc-11eb-9c39-7fa2b0f438f5.png)

**Comment by yashpalzala** [comment]
@darshanclevertap  Any updates regarding the issue ?? 
I think if we are able to solve the missing plugin exception than we might be able to get notifications . 
Because missing plugin exception does not come if the App is in foreground.

**Comment by darshanclevertap** [comment]
@yashpalzala Can you initialize the CleverTap Plugin once before calling the `createNotification` method in the `onBackgroundMessage`?

**Comment by yashpalzala** [comment]
@darshanclevertap 


![image](https://user-images.githubusercontent.com/54407840/119142153-c552d200-ba63-11eb-8ea6-accad652b418.png)

![image](https://user-images.githubusercontent.com/54407840/119142891-9c7f0c80-ba64-11eb-9c9b-8a9d7c3bfa3c.png)

Still the same error

**Comment by epynic** [comment]
@darshanclevertap 

Thats the Log when then notification is sent

![image](https://user-images.githubusercontent.com/2527481/119223769-d3165f00-bb18-11eb-94fe-dbe288c15396.png)

and on notification click we just see the below log

`I/CleverTapResponse(18180): Done processing response!`

as mentioned `setCleverTapPushClickedPayloadReceivedHandler` is not invoked

**Comment by epynic** [comment]
> @darshanclevertap
> 
> ![image](https://user-images.githubusercontent.com/54407840/119142153-c552d200-ba63-11eb-8ea6-accad652b418.png)
> 
> ![image](https://user-images.githubusercontent.com/54407840/119142891-9c7f0c80-ba64-11eb-9c9b-8a9d7c3bfa3c.png)
> 
> Still the same error

old firebase plugin ?

**Comment by yashpalzala** [comment]
> > @darshanclevertap
> > ![image](https://user-images.githubusercontent.com/54407840/119142153-c552d200-ba63-11eb-8ea6-accad652b418.png)
> > ![image](https://user-images.githubusercontent.com/54407840/119142891-9c7f0c80-ba64-11eb-9c9b-8a9d7c3bfa3c.png)
> > Still the same error
> 
> old firebase plugin ?

@epynic This error has nothing to do with firebase . The problem is that when App is onBackground it is not able to find cleveTap SDK . 
Are you able to show notifications successfully when the application is Terminated OR onBackground ??

**Comment by epynic** [comment]
Yes it does @yashpalzala

**Comment by yashpalzala** [comment]
@epynic Can you please elaborate ??

Also if you have done the integration why don't you share it . Would be a
great help.

**Comment by epynic** [comment]
Yes, `FirebaseMessaging.onBackgroundMessage`
![image](https://user-images.githubusercontent.com/2527481/119332592-6cbf4700-bca6-11eb-80f1-70107aa210c9.png)

And the Remote handler
![image](https://user-images.githubusercontent.com/2527481/119332647-819bda80-bca6-11eb-8f54-0554472e313c.png)

Works fine for me, only problem we are not able to get the custom key-value data,

**Comment by epynic** [comment]
@yashpalzala did you get this working ?

**Comment by snghnishant** [comment]
Hey, @darshanclevertap even I tried all this to get the Notification Data for redirecting when the app is in the background or terminated state. This is still not working at all can you please re-open this issue so we can have further discussion in regards to this.

When the app is in Foreground I am able to get the message payload in `FirebaseMessaging.onMessage.listen((RemoteMessage message) {...}` and handle redirections through our custom made alert box. But we also get the Notification rendered in the System Tray, and on clicking that notification the app opens but there's no method handler calls to `void pushClickedPayloadReceived(Map<String, dynamic> message) {...}` which you said will give you the message payload. So basically there's no way by which we can get the message payload on onClick event of the Notification being rendered in system tray in any of the app state.
