### ISSUE TITLE
Functionality to change the default font size and family in style config.

### ISSUE THREAD

**Issue by mrtarunsaraswat** [CleverTap/clevertap-flutter#52]
In our App we want to set same font family for app inbox, is there any way to implement it or any param which we can pass in style config. If not can you implement the small functionality at the earliest.

**Comment by darshanclevertap** [comment]
@sky1095 Here is the [POJO class](https://github.com/CleverTap/clevertap-android-sdk/blob/master/clevertap-core/src/main/java/com/clevertap/android/sdk/inbox/CTInboxMessage.java) for CTInboxMessage. 

`getAllInboxMessages` returns a List of Inbox Messages. You can find the [usage here in the Example project](https://github.com/CleverTap/clevertap-flutter/blob/93ddf67f538d22f6de8a661456a5af23a850bc05/example/lib/main.dart#L784)

If you still face any issues, please let us know
