### ISSUE TITLE
Null exception for recordScreenView call 

### ISSUE THREAD

**Issue by saswatmoo** [CleverTap/clevertap-flutter#54]
I got an exception when over we call CleverTapPlugin.recordScreenView("Screen name");

I am using clevertap_plugin: 1.2.2, flutter 2.2.2

`E/MethodChannel#clevertap_plugin(13623): Failed to handle method call
E/MethodChannel#clevertap_plugin(13623): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
E/MethodChannel#clevertap_plugin(13623): 	at com.clevertap.android.sdk.CleverTapAPI.recordScreen(CleverTapAPI.java:2078)
E/MethodChannel#clevertap_plugin(13623): 	at com.clevertap.clevertap_plugin.CleverTapPlugin.recordScreenView(CleverTapPlugin.java:1164)
E/MethodChannel#clevertap_plugin(13623): 	at com.clevertap.clevertap_plugin.CleverTapPlugin.onMethodCall(CleverTapPlugin.java:282)
E/MethodChannel#clevertap_plugin(13623): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#clevertap_plugin(13623): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#clevertap_plugin(13623): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#clevertap_plugin(13623): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#clevertap_plugin(13623): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#clevertap_plugin(13623): 	at android.os.Looper.loop(Looper.java:197)
E/MethodChannel#clevertap_plugin(13623): 	at android.app.ActivityThread.main(ActivityThread.java:7500)
E/MethodChannel#clevertap_plugin(13623): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#clevertap_plugin(13623): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#clevertap_plugin(13623): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
I/flutter (13623): Invalid token
I/flutter (13623): runZonedGuarded: Caught error in my root zone.
`

**Comment by ashish-pcode** [comment]
Getting the same issue. Please resolve it @darshanclevertap @Aditi3

**Comment by darshanclevertap** [comment]
@saswatmoo Yes, this is currently an issue with our native SDK, the Flutter plugin is a wrapper on top of our native SDK. We will be fixing this soon. I'll keep you posted on the timelines for the same.

**Comment by amgugu111** [comment]
Any progress on this? @darshanclevertap

**Comment by william-ct** [comment]
@amgugu111 This issue has been fixed in [v1.2.3](https://github.com/CleverTap/clevertap-flutter/releases/tag/1.2.3).
