### ISSUE TITLE
Implementation of Notification

### ISSUE THREAD

**Issue by sanjayvramani** [CleverTap/clevertap-flutter#55]
1. I want to receive push messages but don't want to show notification while app is in foreground.
2. I want to show notification when app is in background/killed state.
3. I want to call user defined function while click on notification.
4. How i find that received push message is Simple Notification or InApp Notification.

I am using the flutter for the same. How can i implement above things using flutter.

**Comment by darshanclevertap** [comment]
@sanjayvramani Your questions are very generic? Do you want to implement the above using CleverTap or do you want to learn how to implement using Flutter?

**Comment by sanjayvramani** [comment]
I implemented it, but did not get success on it. So i want the help about the same. I also followed example.

**Comment by darshanclevertap** [comment]
@sanjayvramani Using CleverTap directly, you will not be able to implement these custom requirements. I would suggest you implement the firebase plugin and then intercept the payload received on your end to fulfill your requirements.
