### ISSUE TITLE
Clevertap background notification not doing anything after clicked

### ISSUE THREAD

**Issue by kianutama** [CleverTap/clevertap-flutter#57]
Hi, i have some problems when trying to implement clevertap notification, especially on the background notification. I used `clevertap 1.2.2` and `firebase messaging 9.1.4` for my flutter app that runs on `flutter 2.2.0` and I have been trying to process clevertap background notifications on my app. I already implemented firebase messaging handler to process the notification and I can receive notification from both clevertap and firebase on the **foreground** and when I click both notifications, it redirects me to the correct page.  Here are the logs to the foreground notification.

firebase foreground notification
```
D/FLTFireMsgReceiver( 4078): broadcast received for message
I/flutter ( 4078): FirebaseMessaging onMessage
I/flutter ( 4078): FirebaseMessaging onMessage message data: {cta: update_bakti, notification_id: 5ddf50aef48c3d53742b839c4, source: test, id: 1, body: Test Body, type: action.instant_commission_programs, title: Test Title, click_action: FLUTTER_NOTIFICATION_CLICK}
```

clevertap foreground notification
```
I/CleverTapResponse( 4078): Done processing response!
D/FLTFireMsgReceiver( 4078): broadcast received for message
I/flutter ( 4078): FirebaseMessaging onMessage
I/flutter ( 4078): FirebaseMessaging onMessage message data: {wzrk_acct_id: some-id, pr: , wzrk_push_amp: false, nt: Test notif clevertap, wzrk_pivot: wzrk_default, wzrk_cid: default, wzrk_bi: 2, wzrk_bc: , wzrk_rnv: false, type: action.instant_commission_programs, click_action: FLUTTER_NOTIFICATION_CLICK, wzrk_pn: true, wzrk_id: 0_0, wzrk_ttl: 1625297443, wzrk_dt: FIREBASE, nm: notification testing clevertap}
```

Meanwhile on the background, firebase background notification successfully received the notification, and when it's clicked it called the `onMessageOpenedApp` function and redirect to the correct page. On the other hand, I can only receive the clevertap notification but no `onMessageOpenedApp` being called. 

firebase background notification
```
D/FLTFireMsgReceiver( 4078): broadcast received for message
I/flutter ( 4078): Handling a background message 0:1625211202658277%e745a945e745a945
I/flutter ( 4078): Message data: {cta: update_bakti, notification_id: 5ddf50aef48c3d53742b839c4, source: test, id: 1, body: Test Body, type: action.instant_commission_programs, title: Test Title, click_action: FLUTTER_NOTIFICATION_CLICK}
I/AppStateListener( 4078): onActivityStarted for activity : id.some.package.MainActivity isForegound : true
I/flutter ( 4078): FirebaseMessaging onMessageOpenedApp
I/flutter ( 4078): FirebaseMessaging onMessageOpenedApp message data: {cta: update_bakti, notification_id: 5ddf50aef48c3d53742b839c4, source: test, id: 1, body: Test Body, type: action.instant_commission_programs, title: Test Title, click_action: FLUTTER_NOTIFICATION_CLICK}
```

clevertap background notification
```
D/FLTFireMsgReceiver( 4078): broadcast received for message
I/flutter ( 4078): Handling a background message 0:1625211350076661%e745a945f9fd7ecd
I/flutter ( 4078): Message data: {wzrk_acct_id: some-id, pr: , wzrk_push_amp: false, nt: Test notif clevertap, wzrk_pivot: wzrk_default, wzrk_cid: default, wzrk_bi: 2, wzrk_bc: , wzrk_rnv: false, type: action.instant_commission_programs, click_action: FLUTTER_NOTIFICATION_CLICK, wzrk_pn: true, wzrk_id: 0_0, wzrk_ttl: 1625297747, wzrk_dt: FIREBASE, nm: notification testing clevertap}
I/AppStateListener( 4078): onActivityStarted for activity : id.some.package.MainActivity isForegound : true
I/CleverTapResponse( 4078): Done processing response!
```

Does anyone have any idea why clevertap notification didn't call firebase messaging handler `onMessageOpenedApp` function? Or clevertap background notification needs to be treated differently? Thanks

**Comment by amgugu111** [comment]
Same issue with me. Any update?

**Comment by darshanclevertap** [comment]
@kianutama Sorry for the delay here. Can you please explain the way you're rendering the push notification via CleverTap? Are you calling `createNotification` method of CleverTap inside `onBackgroundMessage` method of Firebase?

If you could share some code snippet, it would help us in understanding this better

**Comment by darshanclevertap** [comment]
Closing this for now. Please reopen the issue if you have any new inputs.
