### ISSUE TITLE
CleverTap Plugin 1.2.2 NullPointerException

### ISSUE THREAD

**Issue by nafas-natasha** [CleverTap/clevertap-flutter#58]
Hello, I've been using the clevertap plugin for Flutter version 1.2.0 since last year to use Native Display, Push Notification, and In App Message campaign. Then I updated it last month to version 1.2.2. Ever since the update, I have been receiving crash report caused by NullPointerException in CleverTapPlugin.java on my app Firebase Crashlytics dashboard. This never happened before with version 1.2.0. 

Here's the crash log detail:
![image](https://user-images.githubusercontent.com/79839684/125906355-f7397544-ea65-4cf2-8d9c-628920b5ccec.png)

![image](https://user-images.githubusercontent.com/79839684/125906433-a66772cc-1277-45ac-9d60-e6ff4a98cab9.png)

Here's my flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.1 20D75 darwin-x64, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.58.1)
[✓] Connected device (2 available)

For now, I decided to roll back to plugin version 1.2.0. I was hoping to use newer version of CleverTap SDK. Please help!
Thank you.

**Comment by nafas-natasha** [comment]
Thank you! will try it again.

**Comment by nafas-natasha** [comment]
Hello, @william-ct sorry to say this but I'm experiencing this null exception again after updating to v.1.3.0. For now, I will rollback to v.1.2.3 until there's a new fix for this.

Here's the crash detail:
![image](https://user-images.githubusercontent.com/79839684/143986733-c81161be-707d-4d04-be0f-95be83365401.png)

another log of the same error:
![image](https://user-images.githubusercontent.com/79839684/143986773-61d44c4d-0746-4bac-b407-fc9e9b164d71.png)

Here's my flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.2, on macOS 12.0.1 21A559 darwin-x64, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.62.3)
[✓] Connected device (1 available)


Please help. Thanks!

**Comment by william-ct** [comment]
Hi @nafas-natasha , we have added a fix for this issue. You can find the commit [here](https://github.com/CleverTap/clevertap-flutter/commit/bda5428ca8f5f2e7c1882e63ff4377049d7069e2). Will be releasing a new version soon. Thanks!
