### ISSUE TITLE
DOB Parameter Format

### ISSUE THREAD

**Issue by Amongsaufa** [CleverTap/clevertap-flutter#6]
Hai CT Team. I got a problem when i set DOB of user with this plugin. There is no DOB user attribute shows in user properties. 
I tried to send DOB like
"DOB" : DateTime.now().toString() or "DOB" : "1998-09-19"

Both of them doesn't work. So how to set DOB from futter?

Thanks

**Comment by darshanclevertap** [comment]
@Amongsaufa This will be fixed in the next release.

**Comment by darshanclevertap** [comment]
@Amongsaufa We will be releasing the next version soon. You will be able to pass DOB as `dd-MM-yyyy` format

**Comment by darshanclevertap** [comment]
@Amongsaufa This has been fixed in v1.1.1. Closing this.
