### ISSUE TITLE
Add example with kotlin

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [CleverTap/clevertap-flutter#60]
Please add example of integrating in Android with kotlin

**Comment by akshaybhange** [comment]
Yes please. My App is not building after updating my `MainActivity.kt`

```
class MyApplication : FlutterApplication() {
    fun onCreate() {
        ActivityLifecycleCallback.register(this) //<--- Add this before super.onCreate()
        super.onCreate()
    }
}
```


Logcat 

```
Running Gradle task 'assembleDebug'...
setu/MainActivity.kt: (6, 23): Unresolved reference: FlutterApplication
setu/MainActivity.kt: (8, 9): Unresolved reference: ActivityLifecycleCallback
setu/MainActivity.kt: (9, 15): Unresolved reference: onCreate

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

```

**Comment by dj-wedig** [comment]
ActivityLifecycleCallback.register(this.application);

Use this line for Kotlin. And don't forget to include "com.clevertap.android.sdk.ActivityLifecycleCallback" as import.

**Comment by darshanclevertap** [comment]
@diego-lipinski-de-castro We will consider migrating the sample app from Java to Kotlin. Meanwhile, if you're facing any issues, please open this thread again to give us details.

@akshaybhange the solution provided by @dj-wedig will work.

Closing this thread as of now.
