### ISSUE TITLE
clever tap configuration

### ISSUE THREAD

**Issue by bironader** [CleverTap/clevertap-flutter#63]
how to init clevertap with account and token in the run time ? 

Is there any way to init the clever tap API with account id and token in flutter directly?

**Comment by darshanclevertap** [comment]
Hi, @bironader sorry for the delay. 
Currently, there is no such way since our flutter SDK. 
I'll take this up as an enhancement request and try to get this prioritized internally.

**Comment by darshanclevertap** [comment]
We are not going to pick this up in the near future. Please raise a support request via CleverTap Dashboard so that it can reach the correct team internally as request.
