### ISSUE TITLE
How to support multiple SDK instance

### ISSUE THREAD

**Issue by sunilm316** [CleverTap/clevertap-flutter#67]
Need to create multiple instances for push to multiple app with different app ids, How to do that?

**Comment by darshanclevertap** [comment]
@sunilm316 Can you explain the use case a bit more? Do you have two CleverTap accounts inside the same app? And you want to send push via both?

**Comment by sunilm316** [comment]
We support multiple countries in a single app, the thing is when we switches one country to another we've written some push events, so this push events should be triggered to respective CleverTap accounts.

**Comment by darshanclevertap** [comment]
@sunilm316 Unfortunately we do not have multi-instance support in our Flutter SDK. I'd suggest you reach out to our support team via the dashboard or your dedicated CSM (if you have one) and raise this with them. They'll be able to provide you a workaround for your use case.

**Comment by sunilm316** [comment]
How CleverTap instances created in flutter sdk?

**Comment by darshanclevertap** [comment]
@sunilm316 CleverTap instance is created with the Account ID and Account token mentioned in the `AndroidManifest.xml` in Android and the` Info.pList` file in iOS.

**Comment by Aditi3** [comment]
Closing it, feel free to reopen if you need further help.
