### ISSUE TITLE
Flutter project with Kotlin config example

### ISSUE THREAD

**Issue by snghnishant** [CleverTap/clevertap-flutter#68]
Please update the documentation or add a branch for this example project using flutter with Kotlin as the compile language

**Comment by darshanclevertap** [comment]
@snghnishant We have noted this as an enhancement into our Flutter roadmap. We will be adding Kotlin code snippets into our documentation soon.

**Comment by DK070202** [comment]
any update on this thread ?

**Comment by leventkantaroglu** [comment]
Is there any progress? Thanks

**Comment by shivamsharma2710** [comment]
@leventkantaroglu I wanted to inform you that we have added Kotlin code snippets to our Flutter documentation. Please feel free to check them out if you are still looking for them.
