### ISSUE TITLE
Notification not rendering in app taskbar for background/terminated app 

### ISSUE THREAD

**Issue by snghnishant** [CleverTap/clevertap-flutter#71]
Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (4 months ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1
firebase_messaging: ^10.0.0
clevertap_plugin: 1.3.0

**Comment by snghnishant** [comment]
Would like to know what does this `CleverTapPlugin.createNotification(data)` actually do and why it's needed to be invoked? It's very difficult to integrate your SDK without any proper documentation. Also, the documentation is a bit outdated as per the latest Cleveratap SDK integration available for flutter. So have created the issue for the same.

**Comment by snghnishant** [comment]
@darshanclevertap quick update: now we are able to see the notification getting rendered in system UI tray, you can close this issue. Thanks!

**Comment by darshanclevertap** [comment]
@snghnishant Before I close the issue, can you share what you have done so that it can help our other users as well?

**Comment by snghnishant** [comment]
@darshanclevertap Eventually It started working today when I tried pushing the notification from the CleverTap dashboard on my FCM token. No changes were made for this. I'll have my custom docs for CleverTap integration linked here with code later for handling the redirects in all three app state(Background, Terminated, Foreground) after testing it on iOS too.

**Comment by ducpn2111** [comment]
@snghnishant Did you have custom docs for CleverTap integration linked here with code later for handling the redirects in all three app state(Background, Terminated, Foreground) yet
