### ISSUE TITLE
Flutter(Android) integration documentation OUTDATED

### ISSUE THREAD

**Issue by snghnishant** [CleverTap/clevertap-flutter#72]
Code-level integration for Clevertap SDK in flutter apps is outdated. 
Suggested changes:-
Move Changelogs updates on the Android part of integration for flutter as mentioned here [CHANGELOGS SDKv4](https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTV4CHANGES.md)

**Comment by darshanclevertap** [comment]
@snghnishant We have reworked our [Flutter documentation](https://developer.clevertap.com/docs/flutter-sdk). I hope it is more helpful now. Please feel free to reopen this issue or create a new one if you face any challenges with the docs.
