### ISSUE TITLE
Unable to install app on Android 12 due to absence of android:exported in manifest

### ISSUE THREAD

**Issue by Irfan-KV** [CleverTap/clevertap-flutter#75]

**Comment by Irfan-KV** [comment]
Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl1559462715.tmp/base.apk (at Binary XML file line #150): com.clevertap.android.sdk.pushnotification.fcm.FcmMessageListenerService: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]

**Comment by william-ct** [comment]
Hi @Irfan-KV, We will be shipping Android 12 support for CleverTap's Flutter SDK soon.Will let you know once we have shipped with the new version of the SDK👍

**Comment by william-ct** [comment]
Hi @Irfan-KV , We have added support for Android 12 in our sample app.
