### ISSUE TITLE
User attributes not registering when running Flutter app on iOS

### ISSUE THREAD

**Issue by CamronLDNF** [CleverTap/clevertap-flutter#76]
I'm using `clevertap_plugin: 1.3.0`. 

To register the user properties, I'm using the `onUserLogin` method. This is what the code looks like (with sample values).

```dart
    var profile = {
      'Name': 'John Doe',
      'Identity': 100,
      'Email': 'johndoe@mail.com',
      'Gender': 'Male',
      'DOB': '27-02-1990',
      'MSG-push': true,
      'MSG-email': true,
    };

    await CleverTapPlugin.onUserLogin(profile);
```

When I run the app on Android, the user properties are registered correctly. When I run the app on iOS (both in emulator and on physical device), the top-level properties (name, email, etc.) and communication preferences are registered correctly BUT the properties that are meant to show up in the **User properties** table do not appear. Again, it works fine with Android but not with iOS. What could be wrong? I have gone through your documentation for Flutter, iOS, and Android, but to no avail.

Here are the screenshots:

**On Android - OK**
![image](https://user-images.githubusercontent.com/43792384/141366386-9217d609-dc74-411d-bf41-0965991b622c.png)

**On iOS - properties not registering**
![image](https://user-images.githubusercontent.com/43792384/141366489-395d6f0b-64d3-4ba4-964a-dddb77ea77e6.png)

**Comment by Aditi3** [comment]
Hi @CamronLDNF 

I verified the aforementioned behaviour for the iOS platform and appears that if you pass the date format as follows then it should work as expected.

```
var dob = new DateTime(2010, 5, 5);
var stuff = ["bags", "shoes", "clothes"];
var profile = {
      'Name': 'John Doe',
      'Identity': 10001,
      'Email': 'johndoe10001@mail.com',
      'Gender': 'Female',
      'Language': 'English',
      'DOB': CleverTapPlugin.getCleverTapDate(dob),
      'stuff': stuff
    };
CleverTapPlugin.onUserLogin(profile);
```

<img width="1174" alt="User-props" src="https://user-images.githubusercontent.com/11608002/141938329-a2d43e1b-e9b6-4272-b7b7-5be0c3abcc1d.png">

**Comment by CamronLDNF** [comment]
@Aditi3 thanks for your response. Per your suggestion, I passed in the profile as follows (removed the attributes we don't use and added communication preferences).

```dart
    var dob = new DateTime(2010, 5, 5);
    var profile = {
      'Name': 'John Doe',
      'Identity': 10001,
      'Email': 'johndoe10001@mail.com',
      'Gender': 'Female',
      'DOB': CleverTapPlugin.getCleverTapDate(dob),
      'MSG-push': true,
      'MSG-email': true,
    };
    CleverTapPlugin.onUserLogin(profile);
```

Although this solves the date issue, it produces a set of other issues now, both in iOS and Android. I've flagged them in the screenshots below. Please let me know.

******
## On iOS
![iOS_1](https://user-images.githubusercontent.com/43792384/142209981-6e8eb71c-688e-4cdc-acc6-196af9451ec9.png)
![iOS_2](https://user-images.githubusercontent.com/43792384/142210000-40ad7633-a377-4a18-a378-59d4992db659.png)
![iOS_3](https://user-images.githubusercontent.com/43792384/142210009-4750b555-0e89-4ed7-bb18-0b9d9e99b808.png)

*****
## On Android
![android_1](https://user-images.githubusercontent.com/43792384/142210040-7b91bad9-bebd-407c-b09c-1690da903ad0.png)
![android_2](https://user-images.githubusercontent.com/43792384/142210048-99d51ca6-7052-44ed-975c-a5ae9d2f62a8.png)
![android_3](https://user-images.githubusercontent.com/43792384/142210057-fc8cc3a3-45a3-4137-a73f-637de9eb9552.png)

**Comment by Aditi3** [comment]
For iOS Mobile Push communication preferences, can you please check if the push token is present on the profile? If the push token is not present then also the communication preference is marked as false. Once, the token gets updated for the user, the user will be subscribed to push.

**Comment by darshanclevertap** [comment]
@CamronLDNF Is this resolved?
