### ISSUE TITLE
Large icon appearing in push notification on Android even when turned off

### ISSUE THREAD

**Issue by CamronLDNF** [CleverTap/clevertap-flutter#79]
See the screenshots below. I have the large icon turned off in the push notification settings, but it still appears in the notification that I receive. Not a blocker issue but it should be adressed at some point.

**The settings**
![image](https://user-images.githubusercontent.com/43792384/141678915-df8d6e65-3d6c-49c7-b9a5-1fb7db7f0431.png)

**The notification**
![Screenshot_20211114-122534](https://user-images.githubusercontent.com/43792384/141679030-297ca5cb-9b29-4d2c-9163-741a5713b8e8.jpg)

**Comment by darshanclevertap** [comment]
By default, the CleverTap SDK shows the app icon as the large icon. The large icon switch on the dashboard is provided in case you want to show some other icon apart from the app icon.

**Comment by CamronLDNF** [comment]
@darshanclevertap I think the default should be to NOT show any large icon at all. Or at least provide an option for hiding the the default large icon. Otherwise as you see in the above screenshot, unless I provide some other large icon (which we shouldn't have to do for each notification) or create a separate channel with a separate small icon, our app icon is displayed twice in the same notification. Looks like a bug. Great if you guys can add that request to your backlog.

In any case, closing this issue.

**Comment by darshanclevertap** [comment]
@CamronLDNF Noted. I will raise this with our product team.
