### ISSUE TITLE
Android MethodChannel does not handle the result correctly therefore the Future on Flutter side never completes

### ISSUE THREAD

**Issue by dtotonfdt** [CleverTap/clevertap-flutter#81]
The method channel implementation on Android side in most cases does not call result.success() which should be used to notify the framework that a processing on the native side has been finished and therefore would allow the Future on Flutter side to be completed.

Example use case:

```
/// Flutter

await CleverTapPlugin.recordEvent('event_name', properties: {'property_name': 'property_value'});
print('This print is never executed!');
```

See CleverTapPlugin.java:

```
    @SuppressWarnings("ConstantConditions")
    @Override
    public void onMethodCall(MethodCall call, @NonNull Result result) {
        switch (call.method) {
            case "setDebugLevel": {
                int debugLevelValue = call.argument("debugLevel");
                CleverTapAPI.setDebugLevel(debugLevelValue);
                result.success(null);
                break;
            }
            case "recordEvent": {
                recordEvent(call, result);
                // TODO: missing result.success(null); call
                break;
            }
        }
   }

    // ...

    private void recordEvent(MethodCall call, Result result) {
        Map<String, Object> eventData = call.argument("eventData");
        String eventName = call.argument("eventName");
        if (isCleverTapNotNull(cleverTapAPI)) {
            this.cleverTapAPI.pushEvent(eventName, eventData);
        } else {
            result.error(TAG, ERROR_MSG, null);
        }
    }
```

In case the recordEvent is successfully executed, the result.success(null) is never called therefore Flutter future hangs. For reference: setDebugLevel method handles the result correctly.

**Comment by william-ct** [comment]
Hey @dtotonfdt . Currently our  method `CleverTapPlugin.recordEvent()` is a fire and forget event, which does not give any callback after the event is raised (you can verify this event on your profile page in dashboard), hence we do not call `result.success(null);` after the event is raised. In the example code you have shared 

```
/// Flutter

await CleverTapPlugin.recordEvent('event_name', properties: {'property_name': 'property_value'});
print('This print is never executed!');
```
You can remove `await` keyword and directly call
 ```
CleverTapPlugin.recordEvent('event_name', properties: {'property_name': 'property_value'});
 print('This print is executed!');
```

Can you elaborate on your use case where you need a callback after an event is raised?

**Comment by dtotonfdt** [comment]
Hello @william-ct, 

if the method is a fire and forget then it would be beneficial if the Flutter interface reflected that. Returning a Future from the current interface can lead to bugs because there is no reason to assume that the Future will never complete and some developers will place await there. E.g. there is a linter rule [unawaited_futures](https://dart-lang.github.io/linter/lints/unawaited_futures.html) that makes sure that you await every Future in async method body.

Proposal:
Methods on Flutter CleverTap interface should have void return type instead of the Future. This will make sure that the fire and forget mechanism is respected.

**Comment by william-ct** [comment]
Hi @dtotonfdt, We've added `result.success(null)` for all fire and forget calls as well. Will add this in the updated version which will be released soon

**Comment by william-ct** [comment]
We have fixed this issue in the latest version of our SDK(v1.4.0). Thanks
