### ISSUE TITLE
Need to read custom key-value pairs passed in a push notification

### ISSUE THREAD

**Issue by iAn-Pinto** [CleverTap/clevertap-flutter#9]
How do I get the custom key-value pairs passed in the clevertap dashboard push notification in my flutter app using this plugin.
I have followed all steps for using the plugin to receive clevertap dashboard campaign push notifications and am receiving the push notification in my system tray. 
I just need which plugin callback method to use to read extra data like the custom key-value pairs passed in the clevertap dashboard.
Please let me know if you need further clarification, as I need to implement push notification urgently in my organisations flutter app using Clevertap flutter plugin.

**Comment by ian-pinto-ketto** [comment]
Kindly provided information on how can get custom key-value pairs passed in Clevertap push notifications in flutter.

**Comment by darshanclevertap** [comment]
@ian-pinto-ketto hi, this would involve adding callbacks in the CleverTap Android and iOS SDK. This is in our roadmap and I'm marking this as enhancement so that you get timely updates on it.

**Comment by darshanclevertap** [comment]
@ian-pinto-ketto @iAn-Pinto 
Our latest version [v1.1.3](https://pub.dev/packages/clevertap_plugin) supports this using the following code
```
_clevertapPlugin.setCleverTapPushClickedPayloadReceivedHandler(pushClickedPayloadReceived);
```
Please check out the sample app's `main.dart` file on how to use it.
Closing this now.
