### ISSUE TITLE
Custom Appinbox data received not parsable for iOS but works for Android

### ISSUE THREAD

**Issue by AjFaboom** [CleverTap/clevertap-flutter#92]
I have integrated Custom AppInbox in my flutter app using your plugin and also have written parser for same but the parser is not working well at iOS end but works for Android very well. Usually it is throwing format exception or unexpected character,etc issues in iOS end. Can anyone help me in this to know whether Appinbox data received for Android & iOS is totally different or same. My emailId to contact is ajinkyam@fermion.org.in . Please reply clevertap team as soon as possible.

**Comment by william-ct** [comment]
Hi @AjFaboom , Can you help us with the stack trace of the parser error which you're facing. Also can you mention which version of ct-flutter-plugin you're using? If you're `CleverTapPlugin.getAllInboxMessages()` to fetch AppInbox data , the response in iOS and Android is different as of now. You can refer to this [issue](https://github.com/CleverTap/clevertap-flutter/issues/77)

**Comment by shivamsharma2710** [comment]
@AjFaboom  Please use CleverTap Flutter SDK version 1.7.0 or onwards. We have streamlined the payload for various callbacks across Android and iOS platforms. Please, refer to the [ChangeLog](https://github.com/CleverTap/clevertap-flutter/releases/tag/1.7.0) for the v1.7.0 release.
